### ISSUE TITLE
[Code health] Noisy logs due to "No geometry data found in feature ..."

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1040]
Local debug log is noisy due to errors of the form:

```
2021-11-12 14:44:32.436 12547-5735/com.google.android.gnd E/StreamUtil: com.google.android.gnd.persistence.local.LocalDataConsistencyException: No geometry data found in feature <featureId>
        at com.google.android.gnd.persistence.local.room.entity.FeatureEntity.toFeature(FeatureEntity.java:164)
        at com.google.android.gnd.persistence.local.room.RoomLocalDataStore.lambda$toFeatures$12(RoomLocalDataStore.java:268)
        at com.google.android.gnd.persistence.local.room.-$$Lambda$RoomLocalDataStore$lWERjY_pxWEM2rVD_SPp5enfYEA.get(Unknown Source:4)
        at com.google.android.gnd.util.StreamUtil.logErrorsAndSkip(StreamUtil.java:36)
        at com.google.android.gnd.persistence.local.room.RoomLocalDataStore.lambda$toFeatures$13(RoomLocalDataStore.java:268)
        at com.google.android.gnd.persistence.local.room.-$$Lambda$RoomLocalDataStore$f-B2LdLurDjADLnJ0ClZeNdTLtM.apply(Unknown Source:4)
        at java8.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:275)
        at java8.util.DelegatingSpliterator$ConsumerDelegate.accept(DelegatingSpliterator.java:93)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
        at java8.util.DelegatingSpliterator.forEachRemaining(DelegatingSpliterator.java:57)
        at java8.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java8.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java8.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:1269)
        at java8.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java8.util.stream.ReferencePipeline.collect(ReferencePipeline.java:702)
        at com.google.android.gnd.persistence.local.room.RoomLocalDataStore.toFeatures(RoomLocalDataStore.java:269)
        at com.google.android.gnd.persistence.local.room.RoomLocalDataStore.lambda$getFeaturesOnceAndStream$11$RoomLocalDataStore(RoomLocalDataStore.java:262)
        at com.google.android.gnd.persistence.local.room.-$$Lambda$RoomLocalDataStore$oU_TKSWbd27MlnZ5rqyR6j_yZQY.apply(Unknown Source:6)
        at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:63)
        at com.akaita.java.rxjava2debug.extensions.FlowableOnAssembly$OnAssemblySubscriber.onNext(FlowableOnAssembly.java:61)
        at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.innerSuccess(FlowableFlatMapMaybe.java:175)
        at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber$InnerObserver.onSuccess(FlowableFlatMapMaybe.java:397)
        at com.akaita.java.rxjava2debug.extensions.MaybeOnAssembly$OnAssemblyMaybeObserver.onSuccess(MaybeOnAssembly.java:68)
        at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:61)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at com.akaita.java.rxjava2debug.extensions.MaybeOnAssemblyCallable.subscribeActual(MaybeOnAssemblyCallable.java:43)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:132)
        at com.akaita.java.rxjava2debug.extensions.FlowableOnAssembly$OnAssemblySubscriber.onNext(FlowableOnAssembly.java:61)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

If these are non-catastrophic a debug or info log message without the stack trace should be sufficient.

**Comment by anandwana001** [comment]
This issue no longer exists, we can close this.

**Comment by gino-m** [comment]
@anandwana001 Please be sure to close obsolete issues as "Not planned" instead of "Completed":

<img width="269" alt="Image" src="https://github.com/user-attachments/assets/6fcb0d12-a9ef-4508-94cf-f935660a2477" />
