### ISSUE TITLE
[Project selector] Dialog opened multiple times on config change

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1084]
1. Sign in
2. Accept ToS
3. When project dialog appears, rotate device
4. Rotate device again
5. Multiple dialogs appear, tapping an item closes top dialog revealing dialog underneath.

This could be causing exception found in Crashlytics:
```
Fatal Exception: java.lang.IllegalStateException: Fragment already added: ProjectSelectorDialogFragment{b2d0f68} (72f78b3b-3565-409b-90a5-2e1a1bd4e222 tag=ProjectSelectorDialogFragment)
       at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:91)
       at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1713)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:415)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2404)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2162)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
       at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:3030)
       at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
       at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at com.google.android.gnd.AbstractActivity.onStart(AbstractActivity.java:73)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1521)
       at android.app.Activity.performStart(Activity.java:7838)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3399)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7697)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by shobhitagarwal1612** [comment]
Project selector dialog is displayed when there is no active project during `onStart()` call. For the given repro steps, it creates a new dialog as nothing has been selected.

**Comment by shobhitagarwal1612** [comment]
There is also a check which only displays the dialog if it is not already visible. This probably means that we are performing the above check too early (i.e. before the last dialog is restored)

**Comment by shobhitagarwal1612** [comment]
The real culprit is ".isVisible()" method. During onStop, it returns false even if the dialog is visible.

Replacing that with the below logic fixes the issue.

```
dialogFragment != null
     && dialogFragment.getDialog() != null
     && dialogFragment.getDialog().isShowing()
     && !dialogFragment.isRemoving()
```

**Comment by gino-m** [comment]
Thanks for reporting this. In general, I feel like there should be a better way of representing the dialog lifecycles. If I understood right skimming the article, it seems there is now support for navigation to dialog destinations. Could this help encapsulate our dialog logic from other fragments?
https://medium.com/androiddevelopers/navigation-component-dialog-destinations-bfeb8b022759

**Comment by shobhitagarwal1612** [comment]
Thanks for the suggestion! Let's try it out.

**Comment by shobhitagarwal1612** [comment]
The navigation component is able to gracefully handle all lifecycle changes. However, it still can't handle the following issues:

1. In some cases, dialog is displayed without any user action. (e.g. ProjectSelectorDialogFragment). Here, we must prevent calling `navigator.navigate` if the fragment is already visible. So the only option is to do a check `current_destination_id != constant_foo_id` which works fine but still looks ugly.

2. We can't replace dialogs with navigation component which pass any non-serializable object to the fragment via constructor. First, we will have to decouple the dialog from `HomeScreenFragment` and move all logic to a new view model which is bind to the dialog.
