### ISSUE TITLE
"Feature not found" errors in prod

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1085]
Haven't tried to repro yet. Could these be caused by a feature deleted locally still being present on the map or open in the UI?

```
Non-fatal Exception: com.google.android.gnd.persistence.remote.NotFoundException: Feature not found fn7oz1A2cvIFZULDJbMk
       at com.google.android.gnd.repository.FeatureRepository.lambda$getFeature$2(FeatureRepository.java:129)
       at com.google.android.gnd.repository.FeatureRepository$$ExternalSyntheticLambda2.call(:2)
       at io.reactivex.internal.operators.single.SingleError.subscribeActual(SingleError.java:36)
       at io.reactivex.Single.subscribe(Single.java:3666)
       at com.akaita.java.rxjava2debug.extensions.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:41)
       at io.reactivex.Single.subscribe(Single.java:3666)
       at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmptySingle$SwitchIfEmptyMaybeObserver.onComplete(MaybeSwitchIfEmptySingle.java:95)
       at com.akaita.java.rxjava2debug.extensions.MaybeOnAssembly$OnAssemblyMaybeObserver.onComplete(MaybeOnAssembly.java:78)
       at io.reactivex.internal.operators.single.SingleFlatMapMaybe$FlatMapMaybeObserver.onComplete(SingleFlatMapMaybe.java:127)
       at com.akaita.java.rxjava2debug.extensions.MaybeOnAssembly$OnAssemblyMaybeObserver.onComplete(MaybeOnAssembly.java:78)
       at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onComplete(MaybeSubscribeOn.java:101)
       at com.akaita.java.rxjava2debug.extensions.MaybeOnAssembly$OnAssemblyMaybeObserver.onComplete(MaybeOnAssembly.java:78)
       at io.reactivex.internal.operators.maybe.MaybeOnErrorComplete$OnErrorCompleteMaybeObserver.onComplete(MaybeOnErrorComplete.java:91)
       at com.akaita.java.rxjava2debug.extensions.MaybeOnAssembly$OnAssemblyMaybeObserver.onComplete(MaybeOnAssembly.java:78)
       at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onComplete(MaybePeek.java:167)
       at com.akaita.java.rxjava2debug.extensions.MaybeOnAssembly$OnAssemblyMaybeObserver.onComplete(MaybeOnAssembly.java:78)
       at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onComplete(MaybeMap.java:99)
       at com.akaita.java.rxjava2debug.extensions.MaybeOnAssembly$OnAssemblyMaybeObserver.onComplete(MaybeOnAssembly.java:78)
       at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:59)
       at io.reactivex.Maybe.subscribe(Maybe.java:4290)
       at com.akaita.java.rxjava2debug.extensions.MaybeOnAssemblyCallable.subscribeActual(MaybeOnAssemblyCallable.java:43)
       at io.reactivex.Maybe.subscribe(Maybe.java:4290)
       at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40)
       at io.reactivex.Maybe.subscribe(Maybe.java:4290)
       at com.akaita.java.rxjava2debug.extensions.MaybeOnAssembly.subscribeActual(MaybeOnAssembly.java:41)
       at io.reactivex.Maybe.subscribe(Maybe.java:4290)
       at io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual(MaybePeek.java:56)
       at io.reactivex.Maybe.subscribe(Maybe.java:4290)
       at com.akaita.java.rxjava2debug.extensions.MaybeOnAssembly.subscribeActual(MaybeOnAssembly.java:41)
       at io.reactivex.Maybe.subscribe(Maybe.java:4290)
       at io.reactivex.internal.operators.maybe.MaybeOnErrorComplete.subscribeActual(MaybeOnErrorComplete.java:40)
       at io.reactivex.Maybe.subscribe(Maybe.java:4290)
       at com.akaita.java.rxjava2debug.extensions.MaybeOnAssembly.subscribeActual(MaybeOnAssembly.java:41)
       at io.reactivex.Maybe.subscribe(Maybe.java:4290)
       at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by gino-m** [comment]
Likely obsolete, we'll reopen if Crashlytics reports these again.
