### ISSUE TITLE
[Testing] Instrumentation tests fail with "Error while connecting UiAutomation"

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1409]
..When run locally from Android Studio UI, we see the following in  logcat:

```
2023-01-10 18:11:34.785 14987-14987/com.google.android.ground E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.ground, PID: 14987
    java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{com.google.android.ground.test/com.google.android.ground.CustomTestRunner}: java.lang.RuntimeException: Error while connecting UiAutomation
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5735)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.RuntimeException: Error while connecting UiAutomation
        at android.app.UiAutomation.connect(UiAutomation.java:239)
        at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2046)
        at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2003)
        at com.google.android.ground.CustomTestRunner.setAnimations(CustomTestRunner.java:59)
        at com.google.android.ground.CustomTestRunner.onCreate(CustomTestRunner.java:48)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5732)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

Exception thrown here:
https://github.com/google/ground-android/blob/704d36429c5dee280a8b6037c9830ed2a99304e3/ground/src/androidTest/java/com/google/android/ground/CustomTestRunner.java#L59

**Comment by gino-m** [comment]
Thrown upstream here:
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/Instrumentation.java;l=2111;bpv=1;bpt=1

**Comment by gino-m** [comment]
I can repro in emulated Pixel 4 API 27 (Android 8.1), also after creating a fresh virtual device.

Switching to Pixel 4 API 31 (Android 12.0) solved this issue.

@shobhitagarwal1612 @JSunde @scolsen FYI.
