### ISSUE TITLE
[Code health] Convert instrumentation tests into unit tests

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1513]
```
java.lang.RuntimeException: Unable to create service com.google.android.ground.persistence.remote.firebase.FirebaseMessagingService: java.lang.IllegalStateException: The component was not created. Check that you have added the HiltAndroidRule.
     FATAL EXCEPTION: main
Process: com.google.android.ground, PID: 14552
java.lang.RuntimeException: Unable to create service com.google.android.ground.persistence.remote.firebase.FirebaseMessagingService: java.lang.IllegalStateException: The component was not created. Check that you have added the HiltAndroidRule.
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4198)
	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalStateException: The component was not created. Check that you have added the HiltAndroidRule.
	at dagger.hilt.internal.Preconditions.checkState(Preconditions.java:83)
	at dagger.hilt.android.internal.testing.TestApplicationComponentManager.generatedComponent(TestApplicationComponentManager.java:96)
	at dagger.hilt.android.testing.HiltTestApplication.generatedComponent(HiltTestApplication.java:50)
	at dagger.hilt.EntryPoints.get(EntryPoints.java:59)
	at dagger.hilt.android.internal.managers.ServiceComponentManager.createComponent(ServiceComponentManager.java:70)
	at dagger.hilt.android.internal.managers.ServiceComponentManager.generatedComponent(ServiceComponentManager.java:58)
	at com.google.android.ground.persistence.remote.firebase.Hilt_FirebaseMessagingService.generatedComponent(Hilt_FirebaseMessagingService.java:56)
	at com.google.android.ground.persistence.remote.firebase.Hilt_FirebaseMessagingService.inject(Hilt_FirebaseMessagingService.java:50)
	at com.google.android.ground.persistence.remote.firebase.Hilt_FirebaseMessagingService.onCreate(Hilt_FirebaseMessagingService.java:27)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4186)
	... 8 more
```

**Comment by shobhitagarwal1612** [comment]
Instrumentation tests are passing locally but fail on firebase test lab

**Comment by gino-m** [comment]
Note that Cloud build status on the project reports "passing" status even though current HEAD doesn't compile due to #1529.

**Comment by scolsen** [comment]
@shobhitagarwal1612 -- assigning to you for now, let me know if you think you can't get to this and we can re-assign!

**Comment by gino-m** [comment]
We spoke. Existing instr. tests mock out nearly all backend services. Perhaps we should convert existing instrumentation tests into UI tests for now?
