### ISSUE TITLE
[Crash] App crashes after completing data collection flow

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1656]
1. Open any job
2. Complete all tasks
3. Click complete
4. Observe that the app crashes

Stacktrace:
```
kotlin.UninitializedPropertyAccessException: lateinit property clusterRenderer has not been initialized
 at com.google.android.ground.ui.map.gms.GoogleMapsFragment.setActiveLocationOfInterest(GoogleMapsFragment.kt:430)
 at com.google.android.ground.ui.home.mapcontainer.HomeScreenMapContainerFragment$onCreate$4.invoke(HomeScreenMapContainerFragment.kt:74)
 at com.google.android.ground.ui.home.mapcontainer.HomeScreenMapContainerFragment$onCreate$4.invoke(HomeScreenMapContainerFragment.kt:72)
 at com.google.android.ground.ui.home.mapcontainer.MapCardAdapter.onBindViewHolder(MapCardAdapter.kt:83)
```

**Comment by shobhitagarwal1612** [comment]
@scolsen This looks related to the clustering logic. Assigning it to you for initial triage.

**Comment by scolsen** [comment]
Taking a quick look at this it seems like the issue is as follows:

- we perform a variety of setup tasks in the map fragment in `onMapReady`, which is used as a callback when the underlying maps API is ready to use
- In the map container, we set some click listeners on other UI elements (e.g. data cards) that call methods without ensuring this callback is called, so they can fire without all the map setup being complete.

In general our current map setup is kind of complicated...maybe we can simplify
