### ISSUE TITLE
Can't sign in due to stale token

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1773]
On sign in seeing the following exception, even after uninstalling and reinstalling the app:

```
 com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The supplied auth credential is malformed or has expired. [ ID Token issued at 1690905940 is stale to sign-in. ]
                 	at com.google.android.gms.internal.firebase-auth-api.zzaap.zza(com.google.firebase:firebase-auth@@22.1.0:30)
                 	at com.google.android.gms.internal.firebase-auth-api.zzabo.zza(com.google.firebase:firebase-auth@@22.1.0:26)
                 	at com.google.android.gms.internal.firebase-auth-api.zzabp.zzl(com.google.firebase:firebase-auth@@22.1.0:1)
                 	at com.google.android.gms.internal.firebase-auth-api.zzabm.zzh(com.google.firebase:firebase-auth@@22.1.0:25)
                 	at com.google.android.gms.internal.firebase-auth-api.zzaan.zzh(com.google.firebase:firebase-auth@@22.1.0:1)
                 	at com.google.android.gms.internal.firebase-auth-api.zzyi.zza(com.google.firebase:firebase-auth@@22.1.0:2)
                 	at com.google.android.gms.internal.firebase-auth-api.zzabx.zzc(com.google.firebase:firebase-auth@@22.1.0:10)
                 	at com.google.android.gms.internal.firebase-auth-api.zzabx.zzb(com.google.firebase:firebase-auth@@22.1.0:14)
                 	at com.google.android.gms.internal.firebase-auth-api.zzabc.zzs(com.google.firebase:firebase-auth@@22.1.0:4)
                 	at com.google.android.gms.internal.firebase-auth-api.zzyp.zzC(com.google.firebase:firebase-auth@@22.1.0:4)
                 	at com.google.android.gms.internal.firebase-auth-api.zzaao.zzw(com.google.firebase:firebase-auth@@22.1.0:3)
                 	at com.google.android.gms.internal.firebase-auth-api.zzzt.zzc(com.google.firebase:firebase-auth@@22.1.0:1)
                 	at com.google.android.gms.internal.firebase-auth-api.zzabq.run(com.google.firebase:firebase-auth@@22.1.0:1)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                 	at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
                 	at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(Unknown Source:4)
                 	at java.lang.Thread.run(Thread.java:1012)
```

This may be due to upgrading to Firebase SDK 32.2.0 in #1772.

Possibly related to https://github.com/firebase/firebase-android-sdk/issues/4823

**Comment by gino-m** [comment]
https://github.com/firebase/flutterfire/issues/3135#issuecomment-676843297 suggested restarting the emulator.

Restarting Android Studio, virtual device, and  emulator and uninstalling/reinstalling the app solved this issue.
