### ISSUE TITLE
ClassNotFoundException on GroundApplication_GeneratedInjector

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1841]
Repro unknown, but Crashlytics reports multiple crashes due to the following:

```
Caused by java.lang.ClassNotFoundException: Didn't find class "com.google.android.ground.GroundApplication_GeneratedInjector" on path: DexPathList[[zip file "/data/app/~~lD6BojKhYN3wTJhygYUTDg==/com.google.android.ground-RoHfUFUCdf__QX2gM4UU2Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~lD6BojKhYN3wTJhygYUTDg==/com.google.android.ground-RoHfUFUCdf__QX2gM4UU2Q==/lib/arm64, /system/lib64, /system_ext/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.google.android.ground.Hilt_GroundApplication.<init>(Hilt_GroundApplication.java:21)
       at com.google.android.ground.GroundApplication.<init>(GroundApplication.kt:32)
       at java.lang.Class.newInstance(Class.java)
       at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
       at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
       at android.app.Instrumentation.newApplication(Instrumentation.java:1282)
       at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
       at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6959)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by gino-m** [comment]
Not seeing this anymore. We can reopen if it reoccures
