### ISSUE TITLE
Multiple `StrictMode` policy violations appear in logs

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1882]
Possible related to #1758 and #1881.
```
12:13:03.606  D  StrictMode policy violation; ~duration=592 ms: android.os.strictmode.DiskReadViolation
                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1666)
                 	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                 	at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
                 	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:8054)
                 	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:313)
                 	at java.io.File.exists(File.java:813)
                 	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:790)
                 	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:781)
                 	at android.app.ContextImpl.getFilesDir(ContextImpl.java:826)
                 	at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:286)
                 	at com.google.android.ground.ui.util.FileUtil.<init>(FileUtil.kt:24)
                 	at com.google.android.ground.DaggerGroundApplication_HiltComponents_SingletonC$SingletonCImpl.fileUtil(DaggerGroundApplication_HiltComponents_SingletonC.java:1898)
                 	at com.google.android.ground.DaggerGroundApplication_HiltComponents_SingletonC$SingletonCImpl.-$$Nest$mfileUtil(Unknown Source:0)
                 	at com.google.android.ground.DaggerGroundApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerGroundApplication_HiltComponents_SingletonC.java:2143)
                 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                 	at com.google.android.ground.DaggerGroundApplication_HiltComponents_SingletonC$ActivityCImpl$SwitchingProvider.get(DaggerGroundApplication_HiltComponents_SingletonC.java:1298)
                 	at com.google.android.ground.ui.common.ViewModelFactory.create(ViewModelFactory.java:48)
                 	at androidx.lifecycle.ViewModelProvider$Factory.create(ViewModelProvider.kt:83)
                 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                 	at com.google.android.ground.ui.common.ViewModelFactory.get(ViewModelFactory.java:65)
                 	at com.google.android.ground.ui.common.ViewModelFactory.get(ViewModelFactory.java:59)
                 	at com.google.android.ground.ui.common.AbstractFragment.getViewModel(AbstractFragment.kt:36)
                 	at com.google.android.ground.ui.home.mapcontainer.HomeScreenMapContainerFragment.onCreate(HomeScreenMapContainerFragment.kt:65)
                 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3099)
                 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
                 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
                 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
                 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1825)
                 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1731)
                 	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
                 	at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.kt:158)
                 	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:53)
                 	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:241)
                 	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
                 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1009)
                 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
                 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1135)
                 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
                 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
                 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:694)
                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                 	at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
                 	at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1409)
12:13:03.606  D  	at com.google.android.ground.databinding.HomeScreenFragBinding.inflate(HomeScreenFragBinding.java:84)
                 	at com.google.android.ground.databinding.HomeScreenFragBinding.inflate(HomeScreenFragBinding.java:70)
                 	at com.google.android.ground.ui.home.HomeScreenFragment.onCreateView(HomeScreenFragment.kt:89)
                 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3113)
                 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
                 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
                 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1825)
                 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
                 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:205)
                 	at android.os.Looper.loop(Looper.java:294)
                 	at android.app.ActivityThread.main(ActivityThread.java:8177)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by gino-m** [comment]
Note that some are also being thrown by Firebase Performance and Kotlin's Rx interop `asFlowable()` method.
