### ISSUE TITLE
App crashes on missing task definition

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1904]
This occurs when zooming into an LOI or POI.

```
15:04:06.332  E  FATAL EXCEPTION: main
                 Process: com.google.android.ground, PID: 21309
                 java.lang.IllegalStateException: Unknown task id BALlgDD4Y0lMlGdkK5sA
                 	at com.google.android.ground.model.job.Job.getTask(Job.kt:34)
                 	at com.google.android.ground.persistence.remote.firebase.schema.SubmissionConverter.putResponse(SubmissionConverter.kt:89)
                 	at com.google.android.ground.persistence.remote.firebase.schema.SubmissionConverter.toResponseMap(SubmissionConverter.kt:75)
                 	at com.google.android.ground.persistence.remote.firebase.schema.SubmissionConverter.toSubmission(SubmissionConverter.kt:60)
                 	at com.google.android.ground.persistence.remote.firebase.schema.SubmissionCollectionReference.submissionsByLocationOfInterestId$lambda$0(SubmissionCollectionReference.kt:35)
                 	at com.google.android.ground.persistence.remote.firebase.schema.SubmissionCollectionReference.$r8$lambda$tKBwySqVOnNIY7mflxiC54292EE(Unknown Source:0)
                 	at com.google.android.ground.persistence.remote.firebase.schema.SubmissionCollectionReference$$ExternalSyntheticLambda0.apply(Unknown Source:4)
                 	at com.google.android.ground.persistence.remote.firebase.base.FluentCollectionReference.runQuery(FluentCollectionReference.kt:48)
                 	at com.google.android.ground.persistence.remote.firebase.base.FluentCollectionReference$runQuery$1.invokeSuspend(Unknown Source:15)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8c4cb2e, Dispatchers.Main.immediate]
```

**Comment by gino-m** [comment]
@shobhitagarwal1612 Why are we downloading `submissionsByLocationOfInterestId` at all? Perhaps this is left over from when we still had a submission list?

**Comment by shobhitagarwal1612** [comment]
We only sync submissions (for an LOI) lazily with remote when displaying submission count in the bottom LOI cards. If we want to use locally cached count, then sync needs to happen in the background.
