### ISSUE TITLE
Force quit on empty `defaultStyle` in job

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1967]
```
11:25:09.554  E  FATAL EXCEPTION: main
                 Process: com.google.android.ground, PID: 28661
                 java.lang.StringIndexOutOfBoundsException: length=0; index=0
                 	at java.lang.String.charAt(Native Method)
                 	at android.graphics.Color.parseColor(Color.java:1383)
                 	at com.google.android.ground.model.job.JobKt.getDefaultColor(Job.kt:41)
                 	at com.google.android.ground.ui.home.mapcontainer.HomeScreenMapContainerViewModel.toFeature(HomeScreenMapContainerViewModel.kt:192)
                 	at com.google.android.ground.ui.home.mapcontainer.HomeScreenMapContainerViewModel.access$toFeature(HomeScreenMapContainerViewModel.kt:62)
                 	at com.google.android.ground.ui.home.mapcontainer.HomeScreenMapContainerViewModel$toFeature$1.invokeSuspend(Unknown Source:15)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:205)
                 	at android.os.Looper.loop(Looper.java:294)
                 	at android.app.ActivityThread.main(ActivityThread.java:8177)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f1ee34b, Dispatchers.Main.immediate]
```

**Comment by JSunde** [comment]
Do we want to just fallback to the old default of `#ff9131` if no color is specified? Or is the issue here on the web side since the color was not populated?
@gino-m

**Comment by gino-m** [comment]
> Do we want to just fallback to the old default of `#ff9131` if no color is specified? Or is the issue here on the web side since the color was not populated? @gino-m

It's both. I would use "0" as default since it makes it easier to detect something when wrong.
