### ISSUE TITLE
Force quit on missing ACL

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2014]
If email isn't found in survey ACLs:

```
android.view.InflateException: Binary XML file line #39 in com.google.android.ground:layout/home_screen_frag: Binary XML file line #39 in com.google.android.ground:layout/home_screen_frag: Error inflating class androidx.fragment.app.FragmentContainerView
                 Caused by: android.view.InflateException: Binary XML file line #39 in com.google.android.ground:layout/home_screen_frag: Error inflating class androidx.fragment.app.FragmentContainerView
                 Caused by: java.lang.IllegalStateException: ACL not found for email  in survey Demo survey
                 	at com.google.android.ground.model.Survey.getRole(Survey.kt:40)
                 	at com.google.android.ground.repository.UserRepository.canUserSubmitData(UserRepository.kt:70)
                 	at com.google.android.ground.ui.home.mapcontainer.HomeScreenMapContainerFragment.onCreate(HomeScreenMapContainerFragment.kt:77)
```

**Comment by shobhitagarwal1612** [comment]
The issue seems to be that the current user email is blank, which seems strange. Looking deeper now.

**Comment by shobhitagarwal1612** [comment]
So we do fallback to empty email when converting from FirebaseUser to local model
