### ISSUE TITLE
Force quit on "Collect data"

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2015]
This occurred when running in emulator, not sure of other repro steps:

```
FATAL EXCEPTION: DefaultDispatcher-worker-7
                 Process: com.google.android.ground, PID: 26165
                 android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8191)
                 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1420)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1353)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3605)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4412)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3605)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.widget.TextView.checkForRelayout(TextView.java:9681)
                 	at android.widget.TextView.setText(TextView.java:6269)
                 	at android.widget.TextView.setText(TextView.java:6097)
                 	at android.widget.TextView.setText(TextView.java:6049)
                 	at com.google.android.ground.ui.home.mapcontainer.cards.MapCardAdapter$LoiViewHolder$bind$1$1.invokeSuspend(MapCardAdapter.kt:157)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d20eaf1, Dispatchers.Default]
```

@shobhitagarwal1612 Are we using the ViewHolder correctly in `MapCardAdapter`?

**Comment by shobhitagarwal1612** [comment]
Trying to reproduce the issue locally. Please add more details on how to reproduce the issue for verification.

**Comment by gino-m** [comment]
> Trying to reproduce the issue locally. Please add more details on how to reproduce the issue for verification.

I couldn't reproduce, but the stack trace provides some clues. The exception occurred when updating `submissions.text` in `LoiViewHolder.bind()`. The exception is complaining that `onBindViewHolder` of `MapCardAdapter` was called on a different thread than the one used to create the view hierarchy. Since `onBindViewHolder` is called by the SDK and not by us, I assume that's already on the main thread, and it's the creation of the task views that needs to be done on the main thred.

**Comment by shobhitagarwal1612** [comment]
IIUC, we are switching to `@ApplicationScope` for fetching the submission count and then updating the text. This is causing an issue because the application scope uses default dispatcher.

**Comment by gino-m** [comment]
> IIUC, we are switching to `@ApplicationScope` for fetching the submission count and then updating the text. This is causing an issue because the application scope uses default dispatcher.

I think we just need to switch to main thread on collect.

**Comment by gino-m** [comment]
I believe this is done by launching the coroutine with Main dispatcher, but using `withContext(IoDispatcher)` in the flow.
