### ISSUE TITLE
Force quit when quickly switching from survey list back to map 

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2056]
Stack trace:
```
17:13:35.081  E  FATAL EXCEPTION: main
                 Process: com.google.android.ground, PID: 17758
                 java.lang.IllegalArgumentException: Unmanaged descriptor
                 	at com.google.maps.api.android.lib6.common.m.b(:com.google.android.gms.dynamite_mapsdynamite@234113031@23.41.13 (100700-0):10)
                 	at com.google.maps.api.android.lib6.impl.w.c(:com.google.android.gms.dynamite_mapsdynamite@234113031@23.41.13 (100700-0):18)
                 	at com.google.maps.api.android.lib6.impl.cw.u(:com.google.android.gms.dynamite_mapsdynamite@234113031@23.41.13 (100700-0):11)
                 	at com.google.android.gms.maps.model.internal.r.bb(:com.google.android.gms.dynamite_mapsdynamite@234113031@23.41.13 (100700-0):347)
                 	at m.fo.onTransact(:com.google.android.gms.dynamite_mapsdynamite@234113031@23.41.13 (100700-0):21)
                 	at android.os.Binder.transact(Binder.java:914)
                 	at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
                 	at com.google.android.gms.internal.maps.zzy.zzs(com.google.android.gms:play-services-maps@@18.1.0:3)
                 	at com.google.android.gms.maps.model.Marker.setIcon(com.google.android.gms:play-services-maps@@18.1.0:2)
                 	at com.google.android.ground.ui.map.gms.FeatureClusterRenderer.onClusterItemUpdated(FeatureClusterRenderer.kt:85)
                 	at com.google.android.ground.ui.map.gms.FeatureClusterRenderer.onClusterItemUpdated(FeatureClusterRenderer.kt:40)
                 	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:1060)
                 	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2400(DefaultClusterRenderer.java:1021)
                 	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:736)
                 	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:707)
                 	at android.os.Handler.dispatchMessage(Handler.java:107)
                 	at android.os.Looper.loop(Looper.java:214)
                 	at android.app.ActivityThread.main(ActivityThread.java:7356)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Likely cause: Marker references were kept around even after map was cleared or reinitialized (https://stackoverflow.com/a/47057898)

**Comment by gino-m** [comment]
Can't repro
