### ISSUE TITLE
Force quit when requesting photo permission

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2085]
Pixel 7 API 33, reported by @amysorto

**Comment by gino-m** [comment]
From Crashlytics, likely related:

```
Fatal Exception: com.google.android.ground.system.PermissionDeniedException:
       at com.google.android.ground.system.PermissionsManager.getPermissionsResult(PermissionsManager.kt:71)
       at com.google.android.ground.system.PermissionsManager.access$getPermissionsResult(PermissionsManager.kt:29)
       at com.google.android.ground.system.PermissionsManager$getPermissionsResult$1.invokeSuspend(:15)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by gino-m** [comment]
Duplicate of #2087
