### ISSUE TITLE
Invalid type in Firebase "job" causes force quit

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2095]
Accidentally added a `job` of type `string` instead of `map`, this causes the app to crash when opening the survey list.

@shobhitagarwal1612 PTAL?

```
Fatal Exception: java.lang.RuntimeException: Could not deserialize object. Can't convert object of type java.lang.String to type com.google.android.ground.persistence.remote.firebase.schema.JobNestedObject (found in field 'jobs.suggestLoiTaskType')
       at com.google.firebase.firestore.util.CustomClassMapper.deserializeError(CustomClassMapper.java:565)
       at com.google.firebase.firestore.util.CustomClassMapper.convertBean(CustomClassMapper.java:546)
       at com.google.firebase.firestore.util.CustomClassMapper.deserializeToClass(CustomClassMapper.java:255)
       at com.google.firebase.firestore.util.CustomClassMapper.deserializeToType(CustomClassMapper.java:194)
       at com.google.firebase.firestore.util.CustomClassMapper.deserializeToParameterizedType(CustomClassMapper.java:293)
       at com.google.firebase.firestore.util.CustomClassMapper.deserializeToType(CustomClassMapper.java:192)
       at com.google.firebase.firestore.util.CustomClassMapper.access$300(CustomClassMapper.java:57)
       at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.deserialize(CustomClassMapper.java:780)
       at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.deserialize(CustomClassMapper.java:743)
       at com.google.firebase.firestore.util.CustomClassMapper.convertBean(CustomClassMapper.java:544)
       at com.google.firebase.firestore.util.CustomClassMapper.deserializeToClass(CustomClassMapper.java:255)
       at com.google.firebase.firestore.util.CustomClassMapper.convertToCustomClass(CustomClassMapper.java:103)
       at com.google.firebase.firestore.DocumentSnapshot.toObject(DocumentSnapshot.java:183)
       at com.google.firebase.firestore.QueryDocumentSnapshot.toObject(QueryDocumentSnapshot.java:116)
       at com.google.firebase.firestore.DocumentSnapshot.toObject(DocumentSnapshot.java:161)
       at com.google.firebase.firestore.QueryDocumentSnapshot.toObject(QueryDocumentSnapshot.java:97)
       at com.google.android.ground.persistence.remote.firebase.schema.SurveyConverter.toSurvey(SurveyConverter.kt:36)
       at com.google.android.ground.persistence.remote.firebase.schema.SurveysCollectionReference$getReadable$$inlined$map$1$2.emit(Emitters.kt:224)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(:14)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7842)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by gino-m** [comment]
We need to catch `Throwable` at `SurveySelectorViewModel:74` and show an error message.
