### ISSUE TITLE
Trending stability issue: SubmitDataUseCase.addLocationOfInterest

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2138]
```
Fatal Exception: java.lang.IllegalStateException: Invalid add LOI task response
       at com.google.android.ground.domain.usecases.submission.SubmitDataUseCase.addLocationOfInterest(SubmitDataUseCase.kt:71)
       at com.google.android.ground.domain.usecases.submission.SubmitDataUseCase.invoke(SubmitDataUseCase.kt:54)
       at com.google.android.ground.ui.datacollection.DataCollectionViewModel$saveChanges$1.invokeSuspend(DataCollectionViewModel.kt:181)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by gino-m** [comment]
Root cause is that `CaptureLocationResult` doesn't extend `GeometryTaskResponse`; `DropAPinTaskViewModel` and `PolygonDrawingViewModel` both use `GeometryTaskResponse`.
