### ISSUE TITLE
[Suggest LOI] Crash

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#2176]
```
java.lang.IllegalStateException: Null LOI ID but no add LOI task
                 	at com.google.android.ground.domain.usecases.submission.SubmitDataUseCase.addLocationOfInterest(SubmitDataUseCase.kt:67)
                 	at com.google.android.ground.domain.usecases.submission.SubmitDataUseCase.invoke(SubmitDataUseCase.kt:54)
                 	at com.google.android.ground.ui.datacollection.DataCollectionViewModel$saveChanges$1.invokeSuspend(DataCollectionViewModel.kt:188)
```

**Comment by scolsen** [comment]
The logs suggest this survey had no suggest task, but the suggestion card was still displayed to me at a far enough zoom level.
