### ISSUE TITLE
App crashes at startup on release builds

### ISSUE THREAD

**Issue by rfontanarosa** [google/ground-android#2226]
```
  init {
    Timber.plant(if (isReleaseBuild()) crashReportingTree else Timber.DebugTree())
  }
```

raises the following exception

```
16:26:54.418  E  FATAL EXCEPTION: main
                 Process: com.google.android.ground.openforis.release, PID: 2664
                 java.lang.RuntimeException: Unable to instantiate application com.google.android.ground.GroundApplication package com.google.android.ground.openforis.release: kotlin.UninitializedPropertyAccessException: lateinit property crashReportingTree has not been initialized
                 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1553)
                 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1463)
                 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7532)
                 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2419)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:257)
                 	at android.os.Looper.loop(Looper.java:368)
                 	at android.app.ActivityThread.main(ActivityThread.java:8832)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
                 Caused by: kotlin.UninitializedPropertyAccessException: lateinit property crashReportingTree has not been initialized
                 	at com.google.android.ground.GroundApplication.getCrashReportingTree(GroundApplication.kt:34)
                 	at com.google.android.ground.GroundApplication.<init>(GroundApplication.kt:38)
                 	at java.lang.Class.newInstance(Native Method)
                 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
                 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
                 	at android.app.Instrumentation.newApplication(Instrumentation.java:1301)
                 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1545)
                 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1463) 
                 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7532) 
                 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2419) 
                 	at android.os.Handler.dispatchMessage(Handler.java:106) 
                 	at android.os.Looper.loopOnce(Looper.java:257) 
                 	at android.os.Looper.loop(Looper.java:368) 
                 	at android.app.ActivityThread.main(ActivityThread.java:8832) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) 
16:26:54.422  E  uah_event_acquire ! cmdId: 0 ,strPkg: com.google.android.ground.openforis.release, strIdent: com.android.server.wm, timeout: 600
```

**Comment by gino-m** [comment]
It appears `crashReportingTree` isn't injected into `GroundApplication`, or it's injected after `getCrashReportingTree()` is invoked at startup. @shobhitagarwal1612 Would you be able to look into this? 🙏
