### ISSUE TITLE
[Force quit] Some offline imagery can't be loaded 

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2234]
At least one image is in BIGTIFF format: For ex 8/86/127.tif

The app force quits when this happens.

```
 com.google.android.ground            E  FATAL EXCEPTION: DefaultDispatcher-worker-4
                                                                                                    Process: com.google.android.ground, PID: 9220
                                                                                                    java.lang.IllegalStateException: Invalid or unsupported TIFF file identifier
                                                                                                        at com.google.android.ground.ui.map.gms.mog.MogMetadataReader.validateFileIdentifier(MogMetadataReader.kt:69)
                                                                                                        at com.google.android.ground.ui.map.gms.mog.MogMetadataReader.readImageFileDirectories(MogMetadataReader.kt:39)
                                                                                                        at com.google.android.ground.ui.map.gms.mog.MogClient.readMogMetadata(MogClient.kt:175)
                                                                                                        at com.google.android.ground.ui.map.gms.mog.MogClient.readMogMetadataAndClose(MogClient.kt:164)


```

**Comment by gino-m** [comment]
@sufyanAbbasi The raw source TIFFs were accidentally uploaded to the Cloud bucket instead of the processed COGs. Transferring the correct data over now, should be ready in a few minutes.
