### ISSUE TITLE
"Permission denied" shown on photo task even when app has permission

### ISSUE THREAD

**Issue by rfontanarosa** [google/ground-android#2268]
There are some issues related to the "Take a photo" task:

1. It shows "Permission denied" dialog instead of the system permission request dialog.
2. Even if the permission is set to "Allow only when using the app" it shows the "Permission denied" dialog

![Screenshot_20240226_170815](https://github.com/google/ground-android/assets/10047945/a539dfd9-a014-43ea-a9e8-fe86d3404e03)

3. Sometimes it crashes returning this error:

```
17:07:12.255  E  FATAL EXCEPTION: main
                 Process: org.openforis.ground, PID: 20452
                 java.lang.IllegalArgumentException: Navigation action/destination org.openforis.ground:id/showCameraPermissionDeniedFragment cannot be found from the current destination Destination(org.openforis.ground:id/cameraPermissionDeniedDialogFragment) label=CameraPermissionDeniedDialogFragment
                 	at androidx.navigation.NavController.navigate(NavController.kt:1540)
                 	at androidx.navigation.NavController.navigate(NavController.kt:1472)
                 	at androidx.navigation.NavController.navigate(NavController.kt:1930)
                 	at com.google.android.ground.MainActivity.onNavigate(MainActivity.kt:93)
                 	at com.google.android.ground.MainActivity.access$onNavigate(MainActivity.kt:46)
                 	at com.google.android.ground.MainActivity$onCreate$2$1.emit(MainActivity.kt:72)
                 	at com.google.android.ground.MainActivity$onCreate$2$1.emit(MainActivity.kt:72)
                 	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:382)
                 	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:233)
                 	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:189)
                 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
                 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
                 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
                 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
                 	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
                 	at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SharedFlow.kt:399)
                 	at kotlinx.coroutines.flow.SharedFlowImpl.emit$suspendImpl(SharedFlow.kt:404)
                 	at kotlinx.coroutines.flow.SharedFlowImpl.emit(Unknown Source:0)
                 	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:382)
                 	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:205)
                 	at android.os.Looper.loop(Looper.java:294)
                 	at android.app.ActivityThread.main(ActivityThread.java:8177)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4d2d982, Dispatchers.Main.immediate]
```

**Comment by gino-m** [comment]
@shobhitagarwal1612 Can you take a look? This is urgent for this week as FAO is going to the field next week. 🙏

**Comment by gino-m** [comment]
@shobhitagarwal1612 Low priority / nice to have: Replace buttons with standard material dialog buttons ("OK" in bottom-right).

**Comment by rfontanarosa** [comment]
<img width="320" alt="Screenshot 2024-02-27 alle 10 06 56" src="https://github.com/google/ground-android/assets/10047945/6ae00ad9-3a0e-49b6-b0cd-6c4520f31f9c">

**Comment by gino-m** [comment]
@shobhitagarwal1612 Possibly related: #2273

**Comment by shobhitagarwal1612** [comment]
The task requests for `WRITE_EXTERNAL_STORAGE` and `CAMERA` permissions. And for api 34, `WRITE_EXTERNAL_STORAGE` is failing
