### ISSUE TITLE
[Take a photo] Clicking "take a photo" crashes app

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2273]
Device detail:

![image](https://github.com/google/ground-android/assets/228050/c64d476b-3730-43d2-af16-7843bea94d7a)

Likely stack trace:

```
Fatal Exception: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority org.openforis.ground
       at androidx.core.content.FileProvider.getFileProviderPathsMetaData(FileProvider.java:688)
       at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:719)
       at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:669)
       at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:451)
       at com.google.android.ground.ui.datacollection.tasks.photo.PhotoTaskFragment.launchPhotoCapture(PhotoTaskFragment.kt:130)
       at com.google.android.ground.ui.datacollection.tasks.photo.PhotoTaskFragment.access$launchPhotoCapture(PhotoTaskFragment.kt:43)
       at com.google.android.ground.ui.datacollection.tasks.photo.PhotoTaskFragment$onTakePhoto$1.invoke(PhotoTaskFragment.kt:125)
       at com.google.android.ground.ui.datacollection.tasks.photo.PhotoTaskFragment$onTakePhoto$1.invoke(PhotoTaskFragment.kt:125)
       at com.google.android.ground.ui.datacollection.tasks.photo.PhotoTaskFragment$obtainCapturePhotoPermissions$2.invokeSuspend(PhotoTaskFragment.kt:116)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```
@shobhitagarwal1612 Could you PTAL?

**Comment by shobhitagarwal1612** [comment]
In `AndroidManifest.xml`, we define file provider authorities as `com.google.android.ground`. I'm guessing that we changed te app id to `org.openforis.ground` but didn't modify `AndroidManifest.xml`

Regardless, we should still handle the exception and show some error text to the user.

**Comment by shobhitagarwal1612** [comment]
@gino-m FYI

**Comment by gino-m** [comment]
> In `AndroidManifest.xml`, we define file provider authorities as `com.google.android.ground`. I'm guessing that we changed te app id to `org.openforis.ground` but didn't modify `AndroidManifest.xml`
> 
> Regardless, we should still handle the exception and show some error text to the user.

That's correct. Perhaps some versions of Android crash, and some refuse permissions. @rfontanarosa is testing now.
