### ISSUE TITLE
App occasionally crashes at startup

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2283]
Stack trace from Crashlytics on ofground v0.0.1:

```
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property adapter has not been initialized
       at com.google.android.ground.ui.home.mapcontainer.HomeScreenMapContainerFragment.setupBottomLoiCards(HomeScreenMapContainerFragment.kt:144)
       at com.google.android.ground.ui.home.mapcontainer.HomeScreenMapContainerFragment.onViewCreated(HomeScreenMapContainerFragment.kt:130)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3137)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1435)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2979)
       at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2890)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3138)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1435)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2979)
       at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2890)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3138)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1435)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2979)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2897)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
       at com.google.android.ground.AbstractActivity.onStart(AbstractActivity.kt:52)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1601)
       at android.app.Activity.performStart(Activity.java:8790)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4043)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:230)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:210)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:182)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2630)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8826)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by gino-m** [comment]
@scolsen It appears that `binding` is sometimes not initialized when `showDataCollectionHint()` is launched in `lifecycleScope` from `onViewCreated()`. This is surprising, since `onViewCreated()` should always be called after `onCreateView()` which initializes the binding. Other methods called from `onViewCreated()` also reference `binding` without issues, so my guess is that it has something to do with the CoroutineScope.
