### ISSUE TITLE
[Geometry tasks] Rotating device causes app to force quit

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2299]
Reported by @lecrabe 

Stack trace:

```
15:10:08.842  E  set_timerslack_ns write failed: Operation not permitted
15:10:15.723  E  FATAL EXCEPTION: main
                 Process: com.google.android.ground, PID: 31929
                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.ground/com.google.android.ground.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.google.android.ground.ui.datacollection.tasks.location.CaptureLocationTaskMapFragment: could not find Fragment constructor
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
                 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4784)
                 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4693)
                 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loop(Looper.java:193)
                 	at android.app.ActivityThread.main(ActivityThread.java:6669)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                 Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.google.android.ground.ui.datacollection.tasks.location.CaptureLocationTaskMapFragment: could not find Fragment constructor
                 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:681)
                 	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
                 	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:507)
                 	at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:81)
                 	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
                 	at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2507)
                 	at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1992)
                 	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1968)
                 	at com.google.android.ground.ui.common.AbstractFragment.onCreate(AbstractFragment.kt:51)
                 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3099)
                 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
                 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
                 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
                 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1435)
                 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2979)
                 	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2886)
                 	at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1993)
                 	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1968)
                 	at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:169)
                 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3099)
                 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
                 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
                 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
                 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1435)
                 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2979)
                 	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2886)
                 	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
                 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:220)
15:10:15.723  E  	at com.google.android.ground.AbstractActivity.onCreate(AbstractActivity.kt:33)
                 	at com.google.android.ground.Hilt_MainActivity.onCreate(Hilt_MainActivity.java:58)
                 	at com.google.android.ground.MainActivity.onCreate(MainActivity.kt:63)
                 	at android.app.Activity.performCreate(Activity.java:7136)
                 	at android.app.Activity.performCreate(Activity.java:7127)
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
                 	... 13 more
                 Caused by: java.lang.NoSuchMethodException: <init> []
                 	at java.lang.Class.getConstructor0(Class.java:2327)
                 	at java.lang.Class.getConstructor(Class.java:1725)
                 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:666)
                 	... 47 more
```

**Comment by gino-m** [comment]
@shobhitagarwal1612 Do you have cycles to investigate?

**Comment by shobhitagarwal1612** [comment]
Looking into it now.

**Comment by shobhitagarwal1612** [comment]
I tried looking into it but haven't found a solution yet. This issue is happening with all map type tasks and not just draw area task. We create a map fragment inside the task fragment. This works fine when opening the data collection fragment but fails when rotating the device.

Do you have any ideas?

**Comment by gino-m** [comment]
The problem appears to be that there's no noarg constructor of the data collection fragments. The fragments should be able to be recreated by their parents on config change, so the viewModel should not be getting passed into the constructor. Instead, the Fragment should try to get the viewModel using the ViewModelFactory, ideally through helper `getViewModel`.

@shobhitagarwal1612 Wdyt?

**Comment by shobhitagarwal1612** [comment]
Makes sense. I'll try to figure out a workaround where we don't have to pass the view models via constructor. Thanks for the help!

**Comment by sufyanAbbasi** [comment]
Chatted with @gino-m, seems like disabling screen rotation would be an acceptable solution in the short term.

**Comment by jcqli** [comment]
Based on Sufy's comment "the app was not designed for landscape, nor larger screens" in https://github.com/google/ground-android/pull/2336, assigning to @vittorino for input. Is it possible to get mocks for the landscape experience? Is there a general practice we can follow?

**Comment by gino-m** [comment]
> Based on Sufy's comment "the app was not designed for landscape, nor larger screens" in #2336, assigning to @vittorino for input. Is it possible to get mocks for the landscape experience? Is there a general practice we can follow?

Let's check with @lecrabe, better tablet support may be more important than landscape.
