### ISSUE TITLE
[Draw an area] App crashes on secondary (non-LOI) geometry tasks when offline

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2310]
On Pixel 7 physical device in Airplane Mode, as a normal data collection task while adding an LOI. Does not occur when connected:

```
Fatal Exception: com.google.android.gms.common.api.ApiException: 8502: SETTINGS_CHANGE_UNAVAILABLE
       at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.1.0:3)
       at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@18.1.0:4)
       at com.google.android.gms.internal.location.zzcq.zzb(com.google.android.gms:play-services-location@@21.0.1:2)
       at com.google.android.gms.internal.location.zzr.zza(com.google.android.gms:play-services-location@@21.0.1:3)
       at com.google.android.gms.internal.location.zzb.onTransact(com.google.android.gms:play-services-location@@21.0.1:3)
       at android.os.Binder.execTransactInternal(Binder.java:1501)
       at android.os.Binder.execTransact(Binder.java:1440)
```

**Comment by sufyanAbbasi** [comment]
I was able to repro this on the LOI task.

**Comment by sufyanAbbasi** [comment]
A similar crash occurs when we try to access fine location without having the necessary permission because the user turned it off:

```
 Process: com.google.android.ground, PID: 26842
 java.lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or
 ACCESS_COARSE_LOCATION
 	at
 com.google.maps.api.android.lib6.impl.bk.J(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18
 (190400-0):11)
 	at
 com.google.android.gms.maps.internal.i.bb(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18
 (190400-0):208)
 	at ff.onTransact(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):4)
 	at android.os.Binder.transact(Binder.java:1183)
 	at
 com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.2.0:2)
 	at
 com.google.android.gms.maps.internal.zzg.setMyLocationEnabled(com.google.android.gms:play-services-maps@@18.2.0:4)
 	at
 com.google.android.gms.maps.GoogleMap.setMyLocationEnabled(com.google.android.gms:play-services-maps@@18.2.0:1)
 	at
 com.google.android.ground.ui.map.gms.GoogleMapsFragment.enableCurrentLocationIndicator(GoogleMapsFragment.kt:233)
 	at
 com.google.android.ground.ui.common.AbstractMapContainerFragment.onLocationLockStateChange(AbstractMapContainerFragment.kt:110)
 	at
 com.google.android.ground.ui.common.AbstractMapContainerFragment.access$onLocationLockStateChange(AbstractMapContainerFragment.kt:35)
 	at
 com.google.android.ground.ui.common.AbstractMapContainerFragment$onMapAttached$3$1.emit(AbstractMapContainerFragment.kt:55)
 	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
 	at
 com.google.android.ground.ui.common.AbstractMapContainerFragment$onMapAttached$3.invokeSuspend(AbstractMapContainerFragment.kt:55)
 	at com.google.android.ground.ui.common.AbstractMapContainerFragment$onMapAttached$3.invoke(Unknown
 Source:8)
 	at com.google.android.ground.ui.common.AbstractMapContainerFragment$onMapAttached$3.invoke(Unknown
 Source:2)
 	at
 com.google.android.ground.ui.common.AbstractFragment$launchWhenStarted$1$1.invokeSuspend(AbstractFragment.kt:140)
 	at com.google.android.ground.ui.common.AbstractFragment$launchWhenStarted$1$1.invoke(Unknown
 Source:8)
 	at com.google.android.ground.ui.common.AbstractFragment$launchWhenStarted$1$1.invoke(Unknown
 Source:4)
 	at
 androidx.lifecycle.RepeatOnLifecycleKt$repeatOnLifecycle$3$1$1$1$1$1$1.invokeSuspend(RepeatOnLifecycle.kt:111)
 	at androidx.lifecycle.RepeatOnLifecycleKt$repeatOnLifecycle$3$1$1$1$1$1$1.invoke(Unknown Source:8)
 	at androidx.lifecycle.RepeatOnLifecycleKt$repeatOnLifecycle$3$1$1$1$1$1$1.invoke(Unknown Source:4)
 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
 	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
 	at
 androidx.lifecycle.RepeatOnLifecycleKt$repeatOnLifecycle$3$1$1$1$1.invokeSuspend(RepeatOnLifecycle.kt:110)
 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
 	at
 kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
 	at com.google.android.ground.ui.common.AbstractFragment.launchWhenStarted(AbstractFragment.kt:140)
 	at
 com.google.android.ground.ui.common.AbstractMapContainerFragment.onMapAttached(AbstractMapContainerFragment.kt:55)
 com.google.android.ground.ui.common.AbstractMapContainerFragment.access$onMapAttached(AbstractMapContainerFragment.kt:35)
 	at
 com.google.android.ground.ui.common.AbstractMapContainerFragment$onViewCreated$1.invoke(AbstractMapContainerFragment.kt:44)
 	at
 com.google.android.ground.ui.common.AbstractMapContainerFragment$onViewCreated$1.invoke(AbstractMapContainerFragment.kt:44)
 	at
 com.google.android.ground.ui.map.gms.GoogleMapsFragment.attachToParent$lambda$2(GoogleMapsFragment.kt:158)
 	at
 com.google.android.ground.ui.map.gms.GoogleMapsFragment.$r8$lambda$iL_M7GXScosSTibOCrT4-sQLXK8(Unknown
 Source:0)
 	at
 com.google.android.ground.ui.map.gms.GoogleMapsFragment$$ExternalSyntheticLambda0.onMapReady(Unknown
 Source:4)
 	at com.google.android.gms.maps.zzau.zzb(com.google.android.gms:play-services-maps@@18.2.0:1)
 	at
 com.google.android.gms.maps.internal.zzas.zza(com.google.android.gms:play-services-maps@@18.2.0:5)
 	at
 com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.2.0:3)
 	at android.os.Binder.transact(Binder.java:1183)
 	at fe.c(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):2)
 	at
 com.google.maps.api.android.lib6.impl.bg.run(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18
 (190400-0):2)
 	at android.os.Handler.handleCallback(Handler.java:958)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loopOnce(Looper.java:205)
 	at android.os.Looper.loop(Looper.java:294)
 	at android.app.ActivityThread.main(ActivityThread.java:8177)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b952b52, Dispatchers.Main.immediate]
```

**Comment by sufyanAbbasi** [comment]
Note: The fallback to requesting course grain access is also blocked on the network... sadly. In other words, we'll need to greedily fetch the user's location even if they didn't give us permission and show the error toast if we run into this state. Is there a consequence for fetching a permission that the user didn't give, like does Android block apps that do this too often or something?
