### ISSUE TITLE
[Crash] java.util.NoSuchElementException in MainActivity.navigateUp

### ISSUE THREAD

**Issue by jcqli** [google/ground-android#2416]
Crash found in Firebase ([link](https://firebase.corp.google.com/u/0/project/of-ground/crashlytics/app/android:org.openforis.ground/issues/ee46493a19f042f03d4013f231803817?time=last-ninety-days&types=crash&sessionEventKey=6619264E031A0001755025E1B3C7A4C6_1935406673516250377))

```
Fatal Exception: java.util.NoSuchElementException: List is empty.
       at kotlin.collections.CollectionsKt__MutableCollectionsKt.removeLast(MutableCollections.kt:260)
       at androidx.navigation.NavController.tryRelaunchUpToExplicitStack(NavController.kt:881)
       at androidx.navigation.NavController.navigateUp(NavController.kt:854)
       at com.google.android.ground.MainActivity.navigateUp(MainActivity.kt:132)
       at com.google.android.ground.MainActivity.onSupportNavigateUp(MainActivity.kt:128)
       at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:276)
       at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
       at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
       at android.view.View.performClick(View.java:7745)
       at android.view.View.performClickInternal(View.java:7722)
       at android.view.View.access$3700(View.java:854)
       at android.view.View$PerformClick.run(View.java:29111)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8319)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```

**Comment by shobhitagarwal1612** [comment]
@gino-m We added some custom key-value pair to help with debugging. Is there any plan to release a new patch to play store?

**Comment by gino-m** [comment]
> @gino-m We added some custom key-value pair to help with debugging. Is there any plan to release a new patch to play store?

We had said we want to have some e2e testing in place before doing any more releases, but perhaps this change can be cherry-picked into a minor patch? @rfontanarosa Wdyt?

**Comment by jcqli** [comment]
Waiting for next release to collect more data
