### ISSUE TITLE
[Offline sync] Firebase unable to connect after Airplane Mode switched off

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#255]
In Android emulator:

1. Turn on Airplane Mode 
2. Add/edit observations
3. Turn off Airplane Mode

The following appears is LogCat twice:
```
2019-12-08 13:09:13.603 14378-14412/com.google.android.gnd I/Firestore: (0.6.6-dev) [zzv]: (4f0526c) Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:125)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
        at java.net.InetAddress.getAllByName(InetAddress.java:752)
        at io.grpc.internal.DnsNameResolver$JdkResolver.resolve(DnsNameResolver.java:497)
        at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:200)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        at libcore.io.Posix.android_getaddrinfo(Native Method)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:106)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74) 
        at java.net.InetAddress.getAllByName(InetAddress.java:752) 
        at io.grpc.internal.DnsNameResolver$JdkResolver.resolve(DnsNameResolver.java:497) 
        at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:200) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
    }.
```

Then:
```
    This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
```

The error loops until  it manages to reconnect (1+ min?).

**Comment by gino-m** [comment]
Assigning to myself to verify if this still occurs.

**Comment by shobhitagarwal1612** [comment]
Unable to reproduce the error.

**Comment by JosephVlzMls** [comment]
I have the same problem, can you tell me how to fix it please?
