### ISSUE TITLE
[Data collection / sync status] App crashes after collecting data offline

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2652]
Crash:

1. Turn on airplane mode
2. Add new LOI with data
3. Turn off airplane mode
4. Tap "Sync status"

Stack trace from Crashlytics:

```
          Fatal Exception: java.lang.IllegalStateException: LOI not found: 6fwrqWRbPUBx6uOdlfWu
       at com.google.android.ground.repository.LocationOfInterestRepository.getOfflineLoi(LocationOfInterestRepository.kt:80)
       at com.google.android.ground.repository.LocationOfInterestRepository$getOfflineLoi$1.invokeSuspend(:15)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by scolsen** [comment]
I can't repro this locally using the provided steps. When I follow them I don't hit a crash. Maybe this was left over data? At any rate let's catch this exception at minimum

**Comment by gino-m** [comment]
Ah, I know! I had updated the survey title while the user was offline. There is likely a race condition on the data upload and survey sync. The latter removes all LOIs and recreates them, which would explain this issue. We should also make sure that the survey sync process doesn't also delete unsynced mutations.

**Comment by sufyanAbbasi** [comment]
I tried your repro steps, messing with the survey description, title, even changed the job name but after reenabling airplane mode, I still got the data points synced! There must be something else missing here...

![Screenshot 2024-08-15 at 6 39 04 PM](https://github.com/user-attachments/assets/0cee4351-da15-4546-a98f-15ffbd4b657d)

**Comment by sufyanAbbasi** [comment]
So the key operation, AFAICT, is here where we query the `locationOfInterestDoa` for the ID:
https://github.com/google/ground-android/blob/43d64b9f8185517541d21312e90644b3d48ac38f/ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomLocationOfInterestStore.kt#L65

When this fails, we throw an error, so we should look into where LOIs are moved in and out of it.

**Comment by gino-m** [comment]
Nice sleuthing, @sufyanAbbasi !

> Or, we could skip LOIs which currently have a LocationOfInterestMutation, since we know those haven't been synced yet.

This sounds like the right approach. Mutex won't help here since worker concurrency is supposed to be managed by the OS. There might be something you can do at that level, but the non-local behavior would be harder to grok than the fix you propose here.

> Maybe this would lead to stale LOIs if a new sync doesn't happen,

We can assume a new sync will happen eventually, and that things are expected to be stale until it does.

Perhaps the easiest approach is to add a value to `LocationOfInterestMutationEntity.state` (`NEW_UNSYNCED`), and LOIs with that state can be ignored on sync?
