### ISSUE TITLE
Data not uploading on local emu Pixel 3 API 28

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2689]
![Screenshot_20240823_110057](https://github.com/user-attachments/assets/658fbf31-4d73-40f0-9ae8-fa114e5263f9)

**Comment by gino-m** [comment]
Likely culprit:

```
2024-08-23 10:57:56.588 20749-20954 LocalMutationSyncWorker com.google.android.ground            D  Syncing 1 changes for LOI sHb9tZNeM4QxPJkJZIvm
2024-08-23 10:57:56.606 20749-20825 FirebaseFi...reProvider com.google.android.ground            E  Singleton provider likely initialized multiple times
                                                                                                    java.lang.IllegalStateException: FirebaseFirestore has already been started and its settings can no longer be changed. You can only call setFirestoreSettings() before calling any other methods on a FirebaseFirestore object.
                                                                                                    	at com.google.firebase.firestore.FirebaseFirestore.setFirestoreSettings(FirebaseFirestore.java:267)
                                                                                                    	at com.google.android.ground.persistence.remote.firebase.FirebaseFirestoreProvider$1.invokeSuspend(FirebaseFirestoreProvider.kt:32)
                                                                                                    	at com.google.android.ground.persistence.remote.firebase.FirebaseFirestoreProvider$1.invoke(Unknown Source:8)
                                                                                                    	at com.google.android.ground.persistence.remote.firebase.FirebaseFirestoreProvider$1.invoke(Unknown Source:2)
                                                                                                    	at com.google.android.ground.util.AsyncSingletonProvider.get(AsyncSingletonProvider.kt:33)
                                                                                                    	at com.google.android.ground.persistence.remote.firebase.FirestoreDataStore.db(FirestoreDataStore.kt:55)
                                                                                                    	at com.google.android.ground.persistence.remote.firebase.FirestoreDataStore.applyMutations(FirestoreDataStore.kt:92)
                                                                                                    	at com.google.android.ground.persistence.sync.LocalMutationSyncWorker.processMutations(LocalMutationSyncWorker.kt:118)
                                                                                                    	at com.google.android.ground.persistence.sync.LocalMutationSyncWorker.access$processMutations(LocalMutationSyncWorker.kt:43)
                                                                                                    	at com.google.android.ground.persistence.sync.LocalMutationSyncWorker$processMutations$2.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by anandwana001** [comment]
Tried multiple combinations and user journeys and it's working for me. But after upload starts, it stuck at media syncing 

@shobhitagarwal1612 any similar use case you have seen so far?

https://github.com/user-attachments/assets/b49ceb7c-25d3-4f75-8e73-d8001e5dd728

**Comment by shobhitagarwal1612** [comment]
I have only tried media syncing with remote firestore. I'm not sure if it ever worked with local emulator. Have you checked the logs when it tries to sync the media?

**Comment by anandwana001** [comment]
Happy Case

```
com.google.android.ground.model.job.Job$TaskNotFoundException: unknown task BgWDCWNYEC0iHYJyyDmv
                                                                                                    	at com.google.android.ground.model.job.Job.getTask(Job.kt:46)
                                                                                                    	at com.google.android.ground.persistence.local.room.converter.SubmissionDeltasConverter.fromString(SubmissionDeltasConverter.kt:67)
                                                                                                    	at com.google.android.ground.persistence.local.room.converter.ConverterExtKt.toModelObject(ConverterExt.kt:339)
```



```
Worker result SUCCESS for Work [ id=08b31df7-d474-428e-8aa7-5bb8cdd9f1d5, tags={ com.google.android.ground.persistence.sync.LocalMutationSyncWorker } ]
2024-08-28 10:57:30.154 24600-24705 WM-WorkerWrapper        com.google.android.ground            I  Setting status to enqueued for 2a24a87d-7191-4c3b-8063-b84845fd4f6e
```

```
Starting media upload for LOI: 8gOBON2QoQoqWGNrtVWf
2024-08-28 10:57:30.177 24600-24950 MediaUploadWorker       com.google.android.ground            D  Starting photo upload. local path: /storage/emulated/0/Android/data/com.google.android.ground/files/Pictures/ZACaZeUyQ0bmpLlDo9Z5-sspqfT52bZrSPoKsLX01.jpg, remote path: user-media/surveys/TX15mIEFDzZDflgtmbQy/submissions/ZACaZeUyQ0bmpLlDo9Z5-sspqfT52bZrSPoKsLX01.jpg
```


Case where internet on off immediately after syncing status
```
 java.util.concurrent.CancellationException: Task was cancelled.
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1183)
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:513)
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
                                                                                                    	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
                                                                                                    	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
2024-08-28 11:01:01.238 24600-25366 LocalMutationSyncWorker com.google.android.ground            D  Local mutation sync failed
                                                                                                    kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@a7847ff
2024-08-28 11:01:01.238 24600-25366 LocalMutationSyncWorker com.google.android.ground            E  Failed to sync changes for LOI TUxyQHG8Sjz8Emr5xLcv
                                                                                                    kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@a7847ff
```


brief is, the job or the worker is getting at such a stage from where it is not able restart it. @shobhitagarwal1612

**Comment by gino-m** [comment]
What is the invalid state which cannot be restarted? @shobhitagarwal1612 does this have to do with the invalid photo path issue which you recently fixed?

**Comment by shobhitagarwal1612** [comment]
> What is the invalid state which cannot be restarted? @shobhitagarwal1612 does this have to do with the invalid photo path issue which you recently fixed?

I had validated that the photo path change worked as expected by uploading a photo to firestore.

**Comment by gino-m** [comment]
> I had validated that the photo path change worked as expected by uploading a photo to firestore.

I was just wondering if that could have also fixed this issue. Any idea why the job could be getting cancelled? 

One problem could be that we enqueue the worker job with `ExistingWorkPolicy.APPEND`. Docs say "Note: When using APPEND with failed or cancelled prerequisites, newly enqueued work will also be marked as failed or cancelled respectively. Use ExistingWorkPolicy.APPEND_OR_REPLACE to create a new chain of work.". Updating remaining uses of that work policy might help here.

**Comment by anandwana001** [comment]
As per me and @shobhitagarwal1612  discussed today, what might be happening here is, as soon as the syncing start and we turn internet off, the job gets cancelled and there is no retry, and it stuck there.

yes, something with the policy, need to check. Will update asap here.
