### ISSUE TITLE
App is crashing on TermsOfServiceFragment

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2703]
Observed in Crashlytics:

```
          Fatal Exception: com.google.firebase.firestore.FirebaseFirestoreException: Failed to get document because the client is offline.
       at com.google.firebase.firestore.DocumentReference.lambda$getViaSnapshotListener$1(DocumentReference.java:331)
       at com.google.firebase.firestore.DocumentReference$$ExternalSyntheticLambda2.onEvent(D8$$SyntheticClass)
       at com.google.firebase.firestore.DocumentReference.lambda$addSnapshotListenerInternal$2$com-google-firebase-firestore-DocumentReference(DocumentReference.java:526)
       at com.google.firebase.firestore.DocumentReference$$ExternalSyntheticLambda1.onEvent(D8$$SyntheticClass)
       at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0$com-google-firebase-firestore-core-AsyncEventListener(AsyncEventListener.java:42)
       at com.google.firebase.firestore.core.AsyncEventListener$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at androidx.credentials.CredentialManager$$ExternalSyntheticLambda0.execute(D8$$SyntheticClass)
       at com.google.firebase.firestore.core.AsyncEventListener.onEvent(AsyncEventListener.java:39)
       at com.google.firebase.firestore.core.QueryListener.raiseInitialEvent(QueryListener.java:196)
       at com.google.firebase.firestore.core.QueryListener.onOnlineStateChanged(QueryListener.java:127)
       at com.google.firebase.firestore.core.EventManager.handleOnlineStateChange(EventManager.java:259)
       at com.google.firebase.firestore.core.SyncEngine.handleOnlineStateChange(SyncEngine.java:422)
       at com.google.firebase.firestore.core.MemoryComponentProvider$RemoteStoreCallback.handleOnlineStateChange(MemoryComponentProvider.java:145)
       at com.google.firebase.firestore.remote.RemoteStore$$ExternalSyntheticLambda1.handleOnlineStateChange(D8$$SyntheticClass)
       at com.google.firebase.firestore.remote.OnlineStateTracker.setAndBroadcastState(OnlineStateTracker.java:181)
       at com.google.firebase.firestore.remote.OnlineStateTracker.handleWatchStreamFailure(OnlineStateTracker.java:154)
       at com.google.firebase.firestore.remote.RemoteStore.handleWatchStreamClose(RemoteStore.java:509)
       at com.google.firebase.firestore.remote.RemoteStore.access$200(RemoteStore.java:60)
       at com.google.firebase.firestore.remote.RemoteStore$1.onClose(RemoteStore.java:188)
       at com.google.firebase.firestore.remote.AbstractStream.close(AbstractStream.java:356)
       at com.google.firebase.firestore.remote.AbstractStream.handleServerClose(AbstractStream.java:410)
       at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onClose$3$com-google-firebase-firestore-remote-AbstractStream$StreamObserver(AbstractStream.java:151)
       at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$ExternalSyntheticLambda3.run(D8$$SyntheticClass)
       at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(AbstractStream.java:67)
       at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onClose(AbstractStream.java:137)
       at com.google.firebase.firestore.remote.FirestoreChannel$1.onClose(FirestoreChannel.java:151)
       at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
       at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
       at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
       at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
       at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
       at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
       at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
       at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
       at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
       at java.lang.Thread.run(Thread.java:923)   
```

@rfontanarosa can you please work with @anandwana001 to repro? Is this happening on @lecrabe 's device?

**Comment by anandwana001** [comment]
@gino-m  Not able to run the fork openForis repo, maybe some login issue, but raising the PR so that we don't miss the beta deadline. 
Trying to repo on OpenFors repo with Roberto

**Comment by gino-m** [comment]
> @gino-m Not able to run the fork openForis repo, maybe some login issue, but raising the PR so that we don't miss the beta deadline. Trying to repo on OpenFors repo with Roberto

That fork only updates the package ID and some basic config, I think it's sufficient to test on this main upstream fork for now.
