### ISSUE TITLE
Status.asException in TermsOfServiceFragment - Version 0.1.8-openforis

### ISSUE THREAD

**Issue by anandwana001** [google/ground-android#2708]
```
  Fatal Exception: com.google.firebase.firestore.FirebaseFirestoreException: PERMISSION_DENIED: Missing or insufficient permissions.
       at com.google.firebase.firestore.util.Util.exceptionFromStatus(Util.java:113)
       at com.google.firebase.firestore.core.EventManager.onError(EventManager.java:247)
       at com.google.firebase.firestore.core.SyncEngine.removeAndCleanupTarget(SyncEngine.java:642)
       at com.google.firebase.firestore.core.SyncEngine.handleRejectedListen(SyncEngine.java:478)
       at com.google.firebase.firestore.core.MemoryComponentProvider$RemoteStoreCallback.handleRejectedListen(MemoryComponentProvider.java:130)
       at com.google.firebase.firestore.remote.RemoteStore.processTargetError(RemoteStore.java:591)
       at com.google.firebase.firestore.remote.RemoteStore.handleWatchChange(RemoteStore.java:474)
       at com.google.firebase.firestore.remote.RemoteStore.access$100(RemoteStore.java:60)
       at com.google.firebase.firestore.remote.RemoteStore$1.onWatchChange(RemoteStore.java:183)
       at com.google.firebase.firestore.remote.WatchStream.onNext(WatchStream.java:109)
       at com.google.firebase.firestore.remote.WatchStream.onNext(WatchStream.java:38)
       at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onNext$1$com-google-firebase-firestore-remote-AbstractStream$StreamObserver(AbstractStream.java:119)
       at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(AbstractStream.java:67)
       at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onNext(AbstractStream.java:110)
       at com.google.firebase.firestore.remote.FirestoreChannel$1.onMessage(FirestoreChannel.java:140)
       at io.grpc.internal.DelayedClientCall$DelayedListener.onMessage(DelayedClientCall.java:473)
       at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:660)
       at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:647)
       at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
       at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
       at java.lang.Thread.run(Thread.java:1012)
        
```

**Comment by anandwana001** [comment]
@gino-m @rfontanarosa Just to  confirm, is there any change in the security rules modification in firebase

**Comment by gino-m** [comment]
There was [this change](https://github.com/google/ground-platform/pull/1999/files#diff-ce870d1f9ea210a62dca7bde304838320545fa2d20803910b26ebcb8a7dd1050), but that shouldn't affect access to the ToS. Since I stopped checking whether the ToS existing before navigating to the ToS page, we may now need to handle the PermissionDeniedException while loading ToS, should the existing error toast and signing the user our.

**Comment by anandwana001** [comment]
Quick doubt @gino-m 
Error is coming on 0.1.8-openforis https://github.com/openforis/ground-android/blob/1cbbf0b8b4617f18fa356b5cadb748fd5a96718e/ground/src/main/java/com/google/android/ground/ui/tos/TermsOfServiceViewModel.kt#L50 which doesn't has our latest fix in it, so once it merged, I think all such cases will be handled

**Comment by anandwana001** [comment]
No more a bug, as this is fixed and released now
