### ISSUE TITLE
PhotoTaskFragment - 0.1.8-openforis

### ISSUE THREAD

**Issue by anandwana001** [google/ground-android#2714]
```
    Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1675454603, result=-1, data=null} to activity {org.openforis.ground/com.google.android.ground.MainActivity}: java.lang.UnsupportedOperationException: Unsupported photo orientation 0
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5572)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5611)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:137)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2434)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:8194)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
        
```

```
  Fatal Exception: java.lang.UnsupportedOperationException: Unsupported photo orientation 0
       at com.google.android.ground.ui.datacollection.tasks.photo.PhotoTaskViewModel.getRotationDegrees(PhotoTaskViewModel.kt:100)
       at com.google.android.ground.ui.datacollection.tasks.photo.PhotoTaskViewModel.savePhotoTaskData(PhotoTaskViewModel.kt:79)
       at com.google.android.ground.ui.datacollection.tasks.photo.PhotoTaskFragment.capturePhotoLauncher$lambda$0(PhotoTaskFragment.kt:69)
       at com.google.android.ground.ui.datacollection.tasks.photo.PhotoTaskFragment.$r8$lambda$U9ze-5hWeW4zZfGsogQlD1W6EPY()
       at com.google.android.ground.ui.datacollection.tasks.photo.PhotoTaskFragment$$ExternalSyntheticLambda0.onActivityResult(D8$$SyntheticClass)
       at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:147)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:320)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.jvm.kt:257)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.jvm.kt:293)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.jvm.kt:142)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.jvm.kt:124)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:3197)
       at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:648)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:304)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1675)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3259)
       at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3184)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:3201)
       at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:648)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:304)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1675)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3259)
       at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3184)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:3201)
       at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:648)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:304)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1675)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3259)
       at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3184)
       at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:274)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:358)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
       at com.google.android.ground.AbstractActivity.onStart(AbstractActivity.kt:53)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
       at android.app.Activity.performStart(Activity.java:8146)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3878)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:226)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:206)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:178)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:241)
       at android.os.Looper.loop(Looper.java:342)
       at android.app.ActivityThread.main(ActivityThread.java:8143)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
        
```

**Comment by anandwana001** [comment]
@shobhitagarwal1612 any idea on this?

**Comment by anandwana001** [comment]
@gino-m This issue is coming in 0.1.8-openforis, but in our lastest build in this repository, this is already fixed
@rfontanarosa

**Comment by shobhitagarwal1612** [comment]
This was already fixed. Is openforis using the latest build at HEAD?

**Comment by shobhitagarwal1612** [comment]
Fixed in https://github.com/google/ground-android/pull/2694
