### ISSUE TITLE
[App Crash] NavigateUp Crash

### ISSUE THREAD

**Issue by anandwana001** [google/ground-android#2817]
```
 Fatal Exception: java.util.NoSuchElementException: List is empty.
       at kotlin.collections.CollectionsKt__MutableCollectionsKt.removeLast(MutableCollections.kt:257)
       at androidx.navigation.NavController.tryRelaunchUpToExplicitStack(NavController.kt:881)
       at androidx.navigation.NavController.navigateUp(NavController.kt:854)
       at com.google.android.ground.MainActivity.navigateUp(MainActivity.kt:193)
       at com.google.android.ground.MainActivity.onSupportNavigateUp(MainActivity.kt:189)
       at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:276)
       at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
       at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:187)
       at android.view.View.performClick(View.java:8047)
       at android.view.View.performClickInternal(View.java:8024)
       at android.view.View.-$$Nest$mperformClickInternal()
       at android.view.View$PerformClick.run(View.java:31890)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
        
```

**Comment by anandwana001** [comment]
Duplicate https://github.com/google/ground-android/issues/2416
