### ISSUE TITLE
No view found for id for fragment DrawAreaTaskMapFragment

### ISSUE THREAD

**Issue by anandwana001** [google/ground-android#2822]
```
 Fatal Exception: java.lang.IllegalArgumentException: No view found for id 0x2f5c3 (unknown) for fragment DrawAreaTaskMapFragment{7766ec7} (4426d0d4-e194-4a27-95a1-a0411234cd89 id=0x2f5c3 tag=DrawAreaTaskMapFragment)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:567)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by anandwana001** [comment]
@sufyanAbbasi As per https://github.com/google/ground-android/pull/2588 any inputs you have?

**Comment by gino-m** [comment]
Duplicate of #2749.
