### ISSUE TITLE
[App Crash] Polygon is not complete

### ISSUE THREAD

**Issue by anandwana001** [google/ground-android#2878]
```
Fatal Exception: java.lang.IllegalStateException: Polygon is not complete
       at com.google.android.ground.ui.datacollection.tasks.polygon.DrawAreaTaskViewModel.completePolygon(DrawAreaTaskViewModel.kt:171)
       at com.google.android.ground.ui.datacollection.tasks.polygon.DrawAreaTaskFragment$onCreateActionButtons$3.invoke(DrawAreaTaskFragment.kt:80)
       at com.google.android.ground.ui.datacollection.tasks.polygon.DrawAreaTaskFragment$onCreateActionButtons$3.invoke(DrawAreaTaskFragment.kt:80)
       at com.google.android.ground.ui.datacollection.components.TaskButton$CreateButton$3.invoke(TaskButton.kt:48)
       at com.google.android.ground.ui.datacollection.components.TaskButton$CreateButton$3.invoke(TaskButton.kt:48)
       at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:987)
       at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:981)
       at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:665)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:544)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:566)
       at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Clickable.kt:947)
       at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:795)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:317)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
       at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:185)
       at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:104)
       at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:113)
       at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1576)
       at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1527)
       at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1466)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:786)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1967)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4531)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:744)
       at android.view.View.dispatchPointerEvent(View.java:16476)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8525)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:8276)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7605)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7662)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7628)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7831)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7636)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7888)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7609)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7662)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7628)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7636)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7609)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:11163)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:11045)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:11001)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:11297)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:296)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:187)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8913)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
        
```

**Comment by anandwana001** [comment]
This is an intentional crash

@shobhitagarwal1612 is there a way to avoid this?

```kt
fun completePolygon() {
    check(LineString(vertices).isClosed()) { "Polygon is not complete" }
    check(!isMarkedComplete) { "Already marked complete" }

    isMarkedComplete = true

    refreshMap()
    setValue(DrawAreaTaskData(Polygon(LinearRing(vertices))))
  }
```

cc @gino-m

**Comment by shobhitagarwal1612** [comment]
This check was implemented to ensure that we don't allow clicking if the polygon is incomplete. That means that the button should be disabled somehow.
