### ISSUE TITLE
FloatingDecimal.readJavaFormatString: NumberTaskFragment

### ISSUE THREAD

**Issue by anandwana001** [google/ground-android#2921]
Surveyidd - Y2Y45SfIjkYlKJS7Ujy9

```
 Fatal Exception: java.lang.NumberFormatException: For input string: "."
       at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
       at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
       at java.lang.Double.parseDouble(Double.java:662)
       at com.google.android.ground.model.submission.NumberTaskData.getValue(NumberTaskData.kt:24)
       at com.google.android.ground.persistence.local.room.converter.ValueJsonConverter.toJsonObject(ValueJsonConverter.kt:50)
       at com.google.android.ground.persistence.local.room.converter.SubmissionDeltasConverter.toString(SubmissionDeltasConverter.kt:46)
       at com.google.android.ground.persistence.local.room.converter.ConverterExtKt.toLocalDataStoreObject(ConverterExt.kt:500)
       at com.google.android.ground.persistence.local.room.stores.RoomSubmissionStore.saveDraftSubmission(RoomSubmissionStore.kt:266)
       at com.google.android.ground.repository.SubmissionRepository.saveDraftSubmission(SubmissionRepository.kt:89)
       at com.google.android.ground.ui.datacollection.DataCollectionViewModel$saveDraft$1.invokeSuspend(DataCollectionViewModel.kt:284)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
        
```

**Comment by kenstershiro** [comment]
@anandwana001 could I ask you in future to add either a link to crashlytics or some info on the frequency of the bug, to help with prioritisation? Thanks
