### ISSUE TITLE
DataCollectionViewModel.onPreviousClicked -IllegalStateException - Check failed.

### ISSUE THREAD

**Issue by anandwana001** [google/ground-android#2938]
```
 Fatal Exception: java.lang.IllegalStateException: Check failed.
       at com.google.android.ground.ui.datacollection.DataCollectionViewModel.onPreviousClicked(DataCollectionViewModel.kt:201)
       at com.google.android.ground.ui.datacollection.tasks.AbstractTaskFragment$moveToPrevious$1.invokeSuspend(AbstractTaskFragment.kt:175)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
       at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
       at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
       at kotlinx.coroutines.BuildersKt.launch(:1)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
       at kotlinx.coroutines.BuildersKt.launch$default(:1)
       at com.google.android.ground.ui.datacollection.tasks.AbstractTaskFragment.moveToPrevious(AbstractTaskFragment.kt:175)
       at com.google.android.ground.ui.datacollection.tasks.AbstractTaskFragment.access$moveToPrevious(AbstractTaskFragment.kt:53)
       at com.google.android.ground.ui.datacollection.tasks.AbstractTaskFragment$addPreviousButton$1.invoke(AbstractTaskFragment.kt:147)
       at com.google.android.ground.ui.datacollection.tasks.AbstractTaskFragment$addPreviousButton$1.invoke(AbstractTaskFragment.kt:147)
       at com.google.android.ground.ui.datacollection.components.TaskButton$CreateButton$7.invoke(TaskButton.kt:52)
       at com.google.android.ground.ui.datacollection.components.TaskButton$CreateButton$7.invoke(TaskButton.kt:52)
       at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:987)
       at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:981)
       at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:665)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:544)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:566)
       at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Clickable.kt:947)
       at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:795)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:317)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
       at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:185)
       at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:104)
       at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:113)
       at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1576)
       at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1527)
       at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1466)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:776)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1967)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4568)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:734)
       at android.view.View.dispatchPointerEvent(View.java:16489)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8602)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:8353)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7682)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7739)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7705)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7908)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7713)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7965)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7686)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7739)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7705)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7713)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7686)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:11250)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:11119)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:11075)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:11384)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:337)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:187)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8934)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
        
```

**Comment by anandwana001** [comment]
not occurring from a long time, will open again if this comes up.
