### ISSUE TITLE
[Auth] Can't sign in

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#294]
Clicking "Sign in with Google" on sign in page and selecting an account has no effect.

The issue appears to be in `Navigator.showSignInScreen`; the id returned by `getNavController().getCurrentDestination().getId()` is not recognized.

Stack trace:
```
2020-01-05 23:22:48.893 31109-31109/com.google.android.gnd E/RxDebug: Unhandled Rx error
    io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalArgumentException: 2131296541 id not found
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
        at com.uber.autodispose.HalfSerializer.onNext(HalfSerializer.java:121)
        at com.uber.autodispose.AutoDisposingObserverImpl.onNext(AutoDisposingObserverImpl.java:76)
        at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:569)
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitNext(BehaviorSubject.java:564)
        at io.reactivex.subjects.BehaviorSubject.onNext(BehaviorSubject.java:268)
        at com.google.android.gnd.system.AuthenticationManager.onActivityResult(AuthenticationManager.java:123)
        at com.google.android.gnd.system.AuthenticationManager.lambda$vqw1QPZqSWMLmiSZ3r0w--0ct1w(AuthenticationManager.java)
        at com.google.android.gnd.system.-$$Lambda$AuthenticationManager$vqw1QPZqSWMLmiSZ3r0w--0ct1w.accept(lambda)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at com.akaita.java.rxjava2debug.extensions.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:55)
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
        at com.google.android.gnd.system.ActivityStreams.onActivityResult(ActivityStreams.java:53)
        at com.google.android.gnd.MainActivity.onActivityResult(MainActivity.java:192)
        at android.app.Activity.dispatchActivityResult(Activity.java:6932)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.IllegalArgumentException: 2131296541 id not found
        at com.google.android.gnd.ui.common.Navigator.showSignInScreen(Navigator.java:126)
        at com.google.android.gnd.MainViewModel.onSignedOut(MainViewModel.java:54)
        at com.google.android.gnd.MainActivity.onSignInError(MainActivity.java:139)
        at com.google.android.gnd.MainActivity.onSignInStateChange(MainActivity.java:131)
        at com.google.android.gnd.MainActivity.lambda$RvpWYbC44xMC5rQnCDl7ZoI8B8A(MainActivity.java)
        at com.google.android.gnd.-$$Lambda$MainActivity$RvpWYbC44xMC5rQnCDl7ZoI8B8A.accept(lambda)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at com.uber.autodispose.HalfSerializer.onNext(HalfSerializer.java:121) 
        at com.uber.autodispose.AutoDisposingObserverImpl.onNext(AutoDisposingObserverImpl.java:76) 
        at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246) 
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:569) 
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitNext(BehaviorSubject.java:564) 
        at io.reactivex.subjects.BehaviorSubject.onNext(BehaviorSubject.java:268) 
        at com.google.android.gnd.system.AuthenticationManager.onActivityResult(AuthenticationManager.java:123) 
        at com.google.android.gnd.system.AuthenticationManager.lambda$vqw1QPZqSWMLmiSZ3r0w--0ct1w(AuthenticationManager.java) 
        at com.google.android.gnd.system.-$$Lambda$AuthenticationManager$vqw1QPZqSWMLmiSZ3r0w--0ct1w.accept(lambda) 
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63) 
        at com.akaita.java.rxjava2debug.extensions.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:55) 
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52) 
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308) 
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228) 
        at com.google.android.gnd.system.ActivityStreams.onActivityResult(ActivityStreams.java:53) 
        at com.google.android.gnd.MainActivity.onActivityResult(MainActivity.java:192) 
        at android.app.Activity.dispatchActivityResult(Activity.java:6932) 
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4085) 
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by shobhitagarwal1612** [comment]
Working on it!

**Comment by shobhitagarwal1612** [comment]
I'm unable to reproduce the bug. @gino-m Can you consistently reproduce the bug?

**Comment by gino-m** [comment]
> I'm unable to reproduce the bug. @gino-m Can you consistently reproduce the bug?

Sorry, I forgot that to repro I had to turn back on airplane mode. Just sent a fix!
