### ISSUE TITLE
Updated app doesn't sync

### ISSUE THREAD

**Issue by jo-spek** [google/ground-android#2951]
A collector in Côte d'Ivoire collected data in survey https://ground.openforis.org/survey/Y2Y45SfIjkYlKJS7Ujy9 on December 13th which haven't synchronized. On December 14 the app was updated to build 0.1.12.

Restarting app and device didn't help. Adding another data point today (Dec 23) also didn't trigger synchronization (even though it worked as a solution in a similar scenario before).

<img src="https://github.com/user-attachments/assets/209e1711-9a8d-44d2-98a5-96920862182d" width="270" height="480" />

<br />
<br />
<br />

**Crashlytics report:** https://console.firebase.google.com/project/of-ground/crashlytics/app/android:org.openforis.ground/issues/37ee83fcb5e7289a3d1b520f2fe72d0d?time=last-seven-days&types=crash&deviceCategories=Tablet&sessionEventKey=67693440031E00015502C33BBCCBF123_2029992606761884163

`          Fatal Exception: java.lang.IllegalArgumentException: Navigation action/destination org.openforis.ground:id/show_sync_status cannot be found from the current destination Destination(org.openforis.ground:id/sync_status_fragment) label=État de synchronisation des données class=com.google.android.ground.ui.syncstatus.SyncStatusFragment
       at androidx.navigation.NavController.navigate(NavController.kt:1691)
       at androidx.navigation.NavController.navigate(NavController.kt:1609)
       at androidx.navigation.NavController.navigate(NavController.kt:2169)
       at com.google.android.ground.MainActivity.onNavigate(MainActivity.kt:157)
       at com.google.android.ground.MainActivity.access$onNavigate(MainActivity.kt:56)
       at com.google.android.ground.MainActivity$onCreate$2$1.emit(MainActivity.kt:82)
       at com.google.android.ground.MainActivity$onCreate$2$1.emit(MainActivity.kt:82)
       at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:382)
       at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(:15)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:235)
       at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
       at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SharedFlow.kt:399)
       at kotlinx.coroutines.flow.SharedFlowImpl.emit$suspendImpl(SharedFlow.kt:404)
       at kotlinx.coroutines.flow.SharedFlowImpl.emit()
       at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:382)
       at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(:15)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

**Comment by gino-m** [comment]
@jo-spek How did you associate that issue with the crash log? Could they be unrelated?

From the screenshot it appears the user is connected to Wifi but with a very weak connection. If the Wifi is taking precedence over the mobile connection that could be causing issues. Please either have them disable Wifi, or move to a location with better Wifi signal.

**Comment by jo-spek** [comment]
@gino-m Associated by device and time. The error occurred precisely when I instructed them to collect that data point called "TEST". Error says "show_sync_status cannot be found from the current destination". 

Will tell them to try again in a better connection environment.

**Comment by gino-m** [comment]
@jo-spek Can you confirm whether this is still an issue?

**Comment by jo-spek** [comment]
Never got a follow up.
