### ISSUE TITLE
[Project activation] Can't reactivate project when opening app w/o network

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#298]
**Describe the bug**
The "Project loading" progress dialog spins forever.

**To Reproduce**
1. Close the app
2. Turn on Airplane Mode
3. Reopen the app

**Comment by gino-m** [comment]
Stack trace:
```
D/ProjectRepository: Failed to load project from remote
    com.google.firebase.firestore.FirebaseFirestoreException: Failed to get document because the client is offline.
        at com.google.firebase.firestore.DocumentReference.lambda$getViaSnapshotListener$1(com.google.firebase:firebase-firestore@@21.3.1:330)
        at com.google.firebase.firestore.DocumentReference$$Lambda$2.onEvent(com.google.firebase:firebase-firestore@@21.3.1)
        at com.google.firebase.firestore.DocumentReference.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@21.3.1:504)
        at com.google.firebase.firestore.DocumentReference$$Lambda$3.onEvent(com.google.firebase:firebase-firestore@@21.3.1)
        at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@21.3.1:42)
        at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(com.google.firebase:firebase-firestore@@21.3.1)
        at com.google.firebase.firestore.util.Executors$$Lambda$1.execute(com.google.firebase:firebase-firestore@@21.3.1)
        at com.google.firebase.firestore.core.AsyncEventListener.onEvent(com.google.firebase:firebase-firestore@@21.3.1:39)
        at com.google.firebase.firestore.core.QueryListener.raiseInitialEvent(com.google.firebase:firebase-firestore@@21.3.1:176)
        at com.google.firebase.firestore.core.QueryListener.onOnlineStateChanged(com.google.firebase:firebase-firestore@@21.3.1:116)
        at com.google.firebase.firestore.core.EventManager.handleOnlineStateChange(com.google.firebase:firebase-firestore@@21.3.1:178)
        at com.google.firebase.firestore.core.SyncEngine.handleOnlineStateChange(com.google.firebase:firebase-firestore@@21.3.1:348)
        at com.google.firebase.firestore.core.FirestoreClient.handleOnlineStateChange(com.google.firebase:firebase-firestore@@21.3.1:331)
        at com.google.firebase.firestore.remote.RemoteStore$$Lambda$1.handleOnlineStateChange(com.google.firebase:firebase-firestore@@21.3.1)
        at com.google.firebase.firestore.remote.OnlineStateTracker.setAndBroadcastState(com.google.firebase:firebase-firestore@@21.3.1:176)
        at com.google.firebase.firestore.remote.OnlineStateTracker.handleWatchStreamFailure(com.google.firebase:firebase-firestore@@21.3.1:149)
        at com.google.firebase.firestore.remote.RemoteStore.handleWatchStreamClose(com.google.firebase:firebase-firestore@@21.3.1:476)
        at com.google.firebase.firestore.remote.RemoteStore.access$200(com.google.firebase:firebase-firestore@@21.3.1:53)
        at com.google.firebase.firestore.remote.RemoteStore$1.onClose(com.google.firebase:firebase-firestore@@21.3.1:181)
        at com.google.firebase.firestore.remote.AbstractStream.close(com.google.firebase:firebase-firestore@@21.3.1:333)
        at com.google.firebase.firestore.remote.AbstractStream.handleServerClose(com.google.firebase:firebase-firestore@@21.3.1:387)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onClose$3(com.google.firebase:firebase-firestore@@21.3.1:151)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$Lambda$4.run(com.google.firebase:firebase-firestore@@21.3.1)
        at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(com.google.firebase:firebase-firestore@@21.3.1:67)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onClose(com.google.firebase:firebase-firestore@@21.3.1:137)
        at com.google.firebase.firestore.remote.FirestoreChannel$1.onClose(com.google.firebase:firebase-firestore@@21.3.1:135)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
```
