### ISSUE TITLE
App crashed on emulator with "Unhandled Rx error" after adding observation

### ISSUE THREAD

**Issue by dturner** [google/ground-android#387]
**Describe the bug**
The app crashed after I tapped "Save" on the Add observation screen. I was running on the Pixel 3 emulator with API 29

**To Reproduce**

- Open Ground app
- Choose "Ground Session 1" project
- Tap the Add FAB
- Choose "Turtle nesting sites"
- Tap Add observation
- Complete the form and tap Save

**Actual behavior**
- App crashed 

**Expected behavior**
- App saves the observation and continues to function normally

**Screenshots**
Stuck on "Saving"

![image](https://user-images.githubusercontent.com/873212/76523122-c51e7600-645f-11ea-8593-3b8cd42c8c7e.png)

ANR

![image](https://user-images.githubusercontent.com/873212/76523145-ce0f4780-645f-11ea-8db3-92f3048d2767.png)

**Logcat output**

2020-03-12 12:39:58.183 20876-20876/? E/gle.android.gn: Unknown bits set in runtime_flags: 0x8000
2020-03-12 12:40:00.009 20876-20876/com.google.android.gnd E/gle.android.gn: Invalid ID 0x00000000.
2020-03-12 12:40:00.023 20876-20876/com.google.android.gnd E/gle.android.gn: Invalid ID 0x00000000.
2020-03-12 12:40:01.154 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:01.917 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:02.194 20876-20876/com.google.android.gnd E/RxDebug: Unhandled Rx error
    java.lang.Throwable: Unknown feature type H5O2sJ38xQg0ufCqPtJJ in lace 1F7aiLqyB6YsTcQF4II5
        at com.google.android.gnd.persistence.remote.firestore.FeatureDoc.toObject(FeatureDoc.java:60)
        at com.google.android.gnd.persistence.remote.firestore.schema.FeaturesCollectionReference.lambda$null$0(FeaturesCollectionReference.java:44)
        at com.google.android.gnd.persistence.remote.firestore.schema.-$$Lambda$FeaturesCollectionReference$s_nmCL3cX7OWKTqDa5ulDpaPt9M.apply(Unknown Source:4)
        at com.google.android.gnd.persistence.remote.firestore.converters.QuerySnapshotConverter.toEvent(QuerySnapshotConverter.java:54)
        at com.google.android.gnd.persistence.remote.firestore.converters.QuerySnapshotConverter.lambda$toEvents$0(QuerySnapshotConverter.java:42)
        at com.google.android.gnd.persistence.remote.firestore.converters.-$$Lambda$QuerySnapshotConverter$5_7lYWh3PRni_P1CDWMi-E4_EZM.apply(Unknown Source:4)
        at java8.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:196)
        at java8.util.DelegatingSpliterator$ConsumerDelegate.accept(DelegatingSpliterator.java:93)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
        at java8.util.DelegatingSpliterator.forEachRemaining(DelegatingSpliterator.java:57)
        at java8.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java8.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java8.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:1269)
        at java8.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java8.util.stream.ReferencePipeline.collect(ReferencePipeline.java:602)
        at com.google.android.gnd.persistence.remote.firestore.converters.QuerySnapshotConverter.toEvents(QuerySnapshotConverter.java:44)
        at com.google.android.gnd.persistence.remote.firestore.schema.FeaturesCollectionReference.lambda$observe$1(FeaturesCollectionReference.java:42)
        at com.google.android.gnd.persistence.remote.firestore.schema.-$$Lambda$FeaturesCollectionReference$HyWPvv9DHP8cvr4d5Y1aB2T7Bes.apply(Unknown Source:4)
        at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:265)
        at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.onNext(FlowableFlattenIterable.java:174)
        at com.akaita.java.rxjava2debug.extensions.FlowableOnAssembly$OnAssemblySubscriber.onNext(FlowableOnAssembly.java:61)
        at io.reactivex.internal.operators.flowable.FlowableCreate$NoOverflowBaseAsyncEmitter.onNext(FlowableCreate.java:403)
        at durdinapps.rxfirebase2.RxFirestore$18$1.onEvent(RxFirestore.java:530)
        at durdinapps.rxfirebase2.RxFirestore$18$1.onEvent(RxFirestore.java:523)
        at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@21.3.1:1046)
        at com.google.firebase.firestore.Query$$Lambda$3.onEvent(Unknown Source:6)
        at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@21.3.1:42)
        at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.Throwable
     Caused by: java.lang.Throwable
     Caused by: java.lang.Throwable
     Caused by: java.lang.Throwable
     Caused by: java.lang.Throwable: caused by com.google.android.gnd.persistence.remote.firestore.DataStoreException: Unknown feature type H5O2sJ38xQg0ufCqPtJJ in lace 1F7aiLqyB6YsTcQF4II5
        at com.google.android.gnd.persistence.remote.firestore.schema.FeaturesCollectionReference.observe(FeaturesCollectionReference.java:40)
2020-03-12 12:40:02.194 20876-20876/com.google.android.gnd E/RxDebug:     at com.google.android.gnd.persistence.remote.firestore.FirestoreDataStore.loadFeaturesOnceAndStreamChanges(FirestoreDataStore.java:81)
        at com.google.android.gnd.repository.FeatureRepository.syncFeatures(FeatureRepository.java:69)
        at com.google.android.gnd.-$$Lambda$dbyFHx1wl_aMwsuiitN2w1J4Oaw.apply(Unknown Source:4)
        at java8.util.Optional.map(Optional.java:265)
        at com.google.android.gnd.MainViewModel.syncFeatures(MainViewModel.java:67)
        at com.google.android.gnd.MainViewModel.lambda$JsQLKvuo5q6ndq0rM_WgqCmXAiU(Unknown Source:0)
        at com.google.android.gnd.-$$Lambda$MainViewModel$JsQLKvuo5q6ndq0rM_WgqCmXAiU.apply(Unknown Source:4)
        at io.reactivex.internal.operators.mixed.FlowableSwitchMapCompletable$SwitchMapCompletableObserver.onNext(FlowableSwitchMapCompletable.java:99)
        at io.reactivex.internal.operators.flowable.FlowableRefCount$RefCountSubscriber.onNext(FlowableRefCount.java:209)
        at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:224)
        at io.reactivex.internal.operators.flowable.FlowableReplay$BoundedReplayBuffer.replay(FlowableReplay.java:850)
        at io.reactivex.internal.operators.flowable.FlowableReplay$ReplaySubscriber.onNext(FlowableReplay.java:388)
        at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.drain(FlowableSwitchMap.java:307)
        at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapInnerSubscriber.onNext(FlowableSwitchMap.java:391)
        at io.reactivex.internal.operators.flowable.FlowableConcatArray$ConcatArraySubscriber.onNext(FlowableConcatArray.java:77)
        at io.reactivex.internal.operators.flowable.FlowableOnErrorReturn$OnErrorReturnSubscriber.onNext(FlowableOnErrorReturn.java:50)
        at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:68)
        at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:132)
        at io.reactivex.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onSuccess(SingleToFlowable.java:62)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:60)
        at io.reactivex.internal.observers.ResumeSingleObserver.onSuccess(ResumeSingleObserver.java:46)
        at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
        at io.reactivex.internal.operators.maybe.MaybeToSingle$ToSingleMaybeSubscriber.onSuccess(MaybeToSingle.java:83)
        at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onSuccess(MaybeSubscribeOn.java:91)
        at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onSuccess(MaybeMap.java:89)
        at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:61)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-03-12 12:40:04.989 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:10.522 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:10.629 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:10.827 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:13.621 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:14.895 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:17.365 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:18.641 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:20.363 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:21.509 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:23.487 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:24.765 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:24.860 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:25.124 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:26.372 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:27.780 20876-20876/com.google.android.gnd E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-03-12 12:40:30.507 20876-20876/com.google.android.gnd E/gle.android.gn: Invalid ID 0x00000000.
2020-03-12 12:40:30.510 20876-20876/com.google.android.gnd E/gle.android.gn: Invalid ID 0x00000000.
2020-03-12 12:40:44.510 20876-20876/com.google.android.gnd E/gle.android.gn: Invalid ID 0x00000000.
2020-03-12 12:40:44.515 20876-20876/com.google.android.gnd E/gle.android.gn: Invalid ID 0x00000000.

**Comment by gino-m** [comment]
Looking at the error message it appears you're using an older build - could you kindly pull from upstream `master` and try again?

**Comment by dturner** [comment]
That was it, sorry for the noise!
