### ISSUE TITLE
[Offline projects] Layers not loaded for some projects

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#393]
..even though present in db, and properly deserialized by converters, layers are sometimes not written to the db. As a result, the layer selector is blank after clicking "+" to add a feature.

**Comment by gino-m** [comment]
Possible culprit:
```
2020-03-13 17:01:50.825 11388-11525/com.google.android.gnd D/ProjectRepository: Error loading project from remote
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gnd.model.layer.Style.getColor()' on a null object reference
        at com.google.android.gnd.persistence.local.room.StyleTypeConverter.toString(StyleTypeConverter.java:29)
        at com.google.android.gnd.persistence.local.room.LayerDao_Impl$3.bind(LayerDao_Impl.java:106)
        at com.google.android.gnd.persistence.local.room.LayerDao_Impl$3.bind(LayerDao_Impl.java:82)
        at androidx.room.EntityDeletionOrUpdateAdapter.handle(EntityDeletionOrUpdateAdapter.java:69)
        at com.google.android.gnd.persistence.local.room.LayerDao_Impl$6.call(LayerDao_Impl.java:168)
        at com.google.android.gnd.persistence.local.room.LayerDao_Impl$6.call(LayerDao_Impl.java:162)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at com.akaita.java.rxjava2debug.extensions.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:41)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.maybe.MaybeFilterSingle.subscribeActual(MaybeFilterSingle.java:40)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at com.akaita.java.rxjava2debug.extensions.MaybeOnAssembly.subscribeActual(MaybeOnAssembly.java:41)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
```
