### ISSUE TITLE
App force quits after downloading offline areas

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#550]
Repro TBD...

**Comment by gino-m** [comment]
This occurred after triggering download of an area over Brazil, and then attempting to exit the offline areas list by clicking the "<-" arrow:

```
2020-11-04 14:02:37.291 21332-21332/com.google.android.gnd E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.gnd, PID: 21332
    java.lang.NullPointerException: Attempt to invoke interface method 'int com.google.android.gnd.ui.map.MapAdapter.getMapType()' on a null object reference
        at com.google.android.gnd.ui.map.gms.GoogleMapsMapProvider.getMapType(GoogleMapsMapProvider.java:81)
        at com.google.android.gnd.ui.home.mapcontainer.MapContainerFragment.showMapTypeSelectorDialog(MapContainerFragment.java:74)
        at com.google.android.gnd.ui.home.mapcontainer.MapContainerFragment.lambda$onViewCreated$1$MapContainerFragment(MapContainerFragment.java:142)
        at com.google.android.gnd.ui.home.mapcontainer.-$$Lambda$MapContainerFragment$PfXYRFfDYFg8uvi0YgqS9tjXzXo.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:144)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:443)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:395)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:51)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2737)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2583)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2739)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

@shobhitagarwal1612 could this be related to the issue we were seeing where the map fragment was not being restored?

**Comment by shobhitagarwal1612** [comment]
I'll take a look in sometime.

**Comment by scolsen** [comment]
This does indeed look the same as the crash that occurs if one switches the map style (satellite/none/etc) and then goes to another context.

**Comment by gino-m** [comment]
Involves changing map style first before entering offline area selector (probably).
