### ISSUE TITLE
After adding an observation the map is fully zoomed in and it's not possible to zoom out

### ISSUE THREAD

**Issue by dturner** [google/ground-android#553]
After adding an observation the map is fully zoomed in and it's not possible to zoom out. 

**Steps to reproduce**
- Load the app and tap on the "Add feature" FAB
- Choose the feature type
- Complete the fields for the observation and tap Save

**Expected behavior**
- The feature marker to appear on the map and for it to be possible to zoom in/out using pinch 

**Actual behavior**
- The feature marker doesn't appear and the map appears to be fully zoomed in. It's also not possible to zoom out. 

**Screenshots**
Here's the view I see after adding a feature and observation
![image](https://user-images.githubusercontent.com/873212/89038293-ff69b080-d337-11ea-8830-d2a924feeb73.png)

Tested on Pixel 2 running Android 11 beta 2.5

**Comment by dturner** [comment]
Seeing this error in logcat 

```
2020-07-31 14:14:57.936 10475-10475/com.google.android.gnd D/FeatureRepository: Invalid features in remote db ignored
    com.google.android.gnd.persistence.remote.DataStoreException: Missing location
        at com.google.android.gnd.persistence.remote.firestore.schema.FeatureConverter.toFeature(FeatureConverter.java:41)
        at com.google.android.gnd.persistence.remote.firestore.schema.FeaturesCollectionReference.lambda$toRemoteDataEvents$1(FeaturesCollectionReference.java:46)
        at com.google.android.gnd.persistence.remote.firestore.schema.-$$Lambda$FeaturesCollectionReference$pZM8llkKADx-Iu6OKgJCl6BtjYQ.apply(Unknown Source:4)
        at com.google.android.gnd.persistence.remote.firestore.schema.QuerySnapshotConverter.toEvent(QuerySnapshotConverter.java:55)
        at com.google.android.gnd.persistence.remote.firestore.schema.QuerySnapshotConverter.lambda$toEvents$0(QuerySnapshotConverter.java:42)
        at com.google.android.gnd.persistence.remote.firestore.schema.-$$Lambda$QuerySnapshotConverter$q3Ornk4k4Bx5XBQwy8u5mcLNy_k.apply(Unknown Source:4)
        at java8.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:196)
        at java8.util.DelegatingSpliterator$ConsumerDelegate.accept(DelegatingSpliterator.java:93)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
        at java8.util.DelegatingSpliterator.forEachRemaining(DelegatingSpliterator.java:57)
        at java8.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java8.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java8.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:1269)
        at java8.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java8.util.stream.ReferencePipeline.collect(ReferencePipeline.java:602)
        at com.google.android.gnd.persistence.remote.firestore.schema.QuerySnapshotConverter.toEvents(QuerySnapshotConverter.java:43)
        at com.google.android.gnd.persistence.remote.firestore.schema.FeaturesCollectionReference.toRemoteDataEvents(FeaturesCollectionReference.java:45)
        at com.google.android.gnd.persistence.remote.firestore.schema.FeaturesCollectionReference.lambda$loadOnceAndStreamChanges$0(FeaturesCollectionReference.java:40)
        at com.google.android.gnd.persistence.remote.firestore.schema.-$$Lambda$FeaturesCollectionReference$QNEdO5fu7f_msfYGOUBLEj0nn4Q.apply(Unknown Source:4)
        at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:265)
        at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.onNext(FlowableFlattenIterable.java:174)
        at com.akaita.java.rxjava2debug.extensions.FlowableOnAssembly$OnAssemblySubscriber.onNext(FlowableOnAssembly.java:61)
        at io.reactivex.internal.operators.flowable.FlowableCreate$NoOverflowBaseAsyncEmitter.onNext(FlowableCreate.java:403)
        at durdinapps.rxfirebase2.RxFirestore$20$1.onEvent(RxFirestore.java:713)
        at durdinapps.rxfirebase2.RxFirestore$20$1.onEvent(RxFirestore.java:706)
        at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@21.4.3:1045)
        at com.google.firebase.firestore.Query$$Lambda$3.onEvent(Unknown Source:6)
        at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@21.4.3:42)
        at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.google.android.gms.internal.tasks.zzb.dispatchMessage(com.google.android.gms:play-services-tasks@@17.1.0:6)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by dturner** [comment]
I think I found the issue. I was using the "Example using latest Firebase" project. Switching to the "Ground App" project and I no longer experience this issue.

**Comment by dturner** [comment]
The difference seems to be that the "Example using latest Firebase" project jumps into adding an observation immediately after the feature has been added, whereas the "Ground App" does not.

**Comment by gino-m** [comment]
Thanks for catching this. Fwiw, I don't think it's blue because it's zoomed out; I believe it's blue because that's the toolbar color extended to 100%.

Likely related to #558 and #556.
