### ISSUE TITLE
First time sign in fails

### ISSUE THREAD

**Issue by dturner** [google/ground-android#562]
Sign in failed the first time I tried it.

**To Reproduce**
1. Install and run a new copy of the app on a device with no user accounts
2. Sign in as normal entering the test user details

**Expected behavior**
After signing in you are taken to the main activity

**Actual behavior**
The sign in dialog disappeared leaving only the sign in button behind it. Tapping the sign in button did nothing. The following error was seen in logcat:

```
2020-08-12 20:07:52.236 6867-6867/com.google.android.gnd V/MainActivity: Lifecycle event: onResume()
2020-08-12 20:07:52.237 6867-6867/com.google.android.gnd V/SignInFragment: Lifecycle event: onResume()
2020-08-12 20:07:52.239 6867-10214/com.google.android.gnd V/FA: Activity resumed, time: 40747070
2020-08-12 20:07:53.052 6867-6897/com.google.android.gnd D/FirebaseAuth: Notifying id token listeners about user ( UPEWRKCb7VNKjVwqfQAe8uU1A4i1 ).
2020-08-12 20:07:53.055 6867-6867/com.google.android.gnd D/MainActivity: Auth status change: SIGNED_IN
2020-08-12 20:07:53.064 6867-8473/com.google.android.gnd E/RxDebug: Unhandled Rx error
    java.lang.IllegalArgumentException: -1 id not found
        at com.google.android.gnd.ui.common.Navigator.showHomeScreen(Navigator.java:113)
        at com.google.android.gnd.MainViewModel.onSignedIn(MainViewModel.java:83)
        at com.google.android.gnd.MainActivity.lambda$onSignInStateChange$2$MainActivity(MainActivity.java:117)
        at com.google.android.gnd.-$$Lambda$MainActivity$jVSeok2KCvmjWQGUjGf1FHZaigk.run(Unknown Source:2)
        at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:53)
        at com.uber.autodispose.AutoDisposingCompletableObserverImpl.onComplete(AutoDisposingCompletableObserverImpl.java:85)
        at com.akaita.java.rxjava2debug.extensions.CompletableOnAssembly$OnAssemblyCompletableObserver.onComplete(CompletableOnAssembly.java:71)
        at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by dturner** [comment]
Test device: Pixel 4A running Android 11 Beta (RP1A.200720.011).

**Comment by dturner** [comment]
Able to reproduce on Pixel 2 running Android 11 Beta 3 (RPB3.207716.003)

**Comment by gino-m** [comment]
@dturner Thanks for filing. Did it only fail the first time, i.e. did subsequent attempts work?

**Comment by gino-m** [comment]
@dturner Also, did you move your SHA-1 from the old to the new development Firebase instance?

**Comment by shobhitagarwal1612** [comment]
I tried to reproduce the bug but couldn't. 
@dturner Were you able to reproduce it consistently or was it flaky?

**Comment by gino-m** [comment]
I saw this again after switching Firebase projects. Subsequent sign ins success, so assigning P1 priority.

**Comment by gino-m** [comment]
Can no longer reproduce. One of our fixes to Navigator likely resolved this.
