### ISSUE TITLE
[Map] Force quit after changing map type

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#627]
To repro:
1. Select a map type (e.g. Normal)
2. Tap a point
3. Tap an an observation or add a new one
4. Click save

Click "<-" to return to the map, the app will force quit with the following exception:

```
2020-11-17 17:40:36.002 5804-5804/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.gnd, PID: 5804
    java.lang.NullPointerException: Attempt to invoke interface method 'int com.google.android.gnd.ui.map.MapAdapter.getMapType()' on a null object reference
        at com.google.android.gnd.ui.map.gms.GoogleMapsMapProvider.getMapType(GoogleMapsMapProvider.java:81)
        at com.google.android.gnd.ui.home.mapcontainer.MapContainerFragment.showMapTypeSelectorDialog(MapContainerFragment.java:74)
        at com.google.android.gnd.ui.home.mapcontainer.MapContainerFragment.lambda$onViewCreated$1$MapContainerFragment(MapContainerFragment.java:142)
        at com.google.android.gnd.ui.home.mapcontainer.-$$Lambda$MapContainerFragment$PfXYRFfDYFg8uvi0YgqS9tjXzXo.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:144)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:443)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:395)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:51)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2737)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2583)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2739)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by shobhitagarwal1612** [comment]
I couldn't reproduce the error. Also the stacktrace attached above shows old line number which tells me that the error wasn't produced on latest master.
`com.google.android.gnd.ui.home.mapcontainer.MapContainerFragment.showMapTypeSelectorDialog(MapContainerFragment.java:74)`

@gino-m Could you please update your local branch and test if you can repro the bug?

**Comment by gino-m** [comment]
Trying to repro, but currently blocked on #631. I'll check again once that's resolved.

**Comment by gino-m** [comment]
I tried several different ways but was unable to repro. Closing this issue 👏!
