### ISSUE TITLE
[Add/edit Observation] Force quit when photo not found

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#827]
Not sure how to repro yet, occurred while debugging other issues. Stack trace:

```
2021-05-25 12:55:10.340 25050-25212/com.google.android.gnd E/StorageException: {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
    java.io.IOException: {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
        at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:434)
        at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:451)
        at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:442)
        at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:272)
        at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:286)
        at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:70)
        at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:62)
        at com.google.firebase.storage.GetDownloadUrlTask.run(GetDownloadUrlTask.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

@shobhitagarwal1612 FYI.

**Comment by shobhitagarwal1612** [comment]
Looking at the stack trace, 
it seems like the app was trying to read a file from firebase storage which isn't available anymore.
We should handle this case and show an appropriate message to the user (also fix the value in db?) .

**Comment by gino-m** [comment]
Actually this is expected to happen in the period before the photo is saved to remote. The problem is that StorageException's constructor logs the error even if we handle it. The crash is likely to have been unrelated to this message, possible a duplicate of #828.
