### ISSUE TITLE
[Feature details] Tapping add observation button has no effect

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#850]
After adding an observation, navigating to a polygon, selecting polygon, and trying to add an observation by tapping "+ Observation":

```
2021-06-04 11:45:37.154 2125-2125/com.google.android.gnd E/RxDebug: Unhandled Rx error
    io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalArgumentException: Navigation action/destination com.google.android.gnd:id/addObservation cannot be found from the current destination Destination(com.google.android.gnd:id/edit_observation_fragment) label=edit_observation_frag class=com.google.android.gnd.ui.editobservation.EditObservationFragment
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
        at com.uber.autodispose.HalfSerializer.onNext(HalfSerializer.java:121)
        at com.uber.autodispose.AutoDisposingObserverImpl.onNext(AutoDisposingObserverImpl.java:85)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
        at com.google.android.gnd.ui.common.Navigator.navigate(Navigator.java:56)
        at com.google.android.gnd.ui.home.HomeScreenViewModel.addObservation(HomeScreenViewModel.java:273)
        at com.google.android.gnd.databinding.FeatureDetailsChromeBindingImpl._internalCallbackOnClick(FeatureDetailsChromeBindingImpl.java:178)
        at com.google.android.gnd.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:7448)
        at android.widget.CompoundButton.performClick(CompoundButton.java:144)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: Navigation action/destination com.google.android.gnd:id/addObservation cannot be found from the current destination Destination(com.google.android.gnd:id/edit_observation_fragment) label=edit_observation_frag class=com.google.android.gnd.ui.editobservation.EditObservationFragment
        at androidx.navigation.NavController.navigate(NavController.java:938)
        at androidx.navigation.NavController.navigate(NavController.java:875)
        at androidx.navigation.NavController.navigate(NavController.java:861)
        at androidx.navigation.NavController.navigate(NavController.java:1150)
        at com.google.android.gnd.MainActivity.onNavigate(MainActivity.java:92)
        at com.google.android.gnd.MainActivity.lambda$UhXXmklGnOm0StUNUHDsvULV-SY(Unknown Source:0)
        at com.google.android.gnd.-$$Lambda$MainActivity$UhXXmklGnOm0StUNUHDsvULV-SY.accept(Unknown Source:4)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at com.uber.autodispose.HalfSerializer.onNext(HalfSerializer.java:121) 
        at com.uber.autodispose.AutoDisposingObserverImpl.onNext(AutoDisposingObserverImpl.java:85) 
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308) 
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228) 
        at com.google.android.gnd.ui.common.Navigator.navigate(Navigator.java:56) 
        at com.google.android.gnd.ui.home.HomeScreenViewModel.addObservation(HomeScreenViewModel.java:273) 
        at com.google.android.gnd.databinding.FeatureDetailsChromeBindingImpl._internalCallbackOnClick(FeatureDetailsChromeBindingImpl.java:178) 
        at com.google.android.gnd.generated.callback.OnClickListener.onClick(OnClickListener.java:11) 
        at android.view.View.performClick(View.java:7448) 
        at android.widget.CompoundButton.performClick(CompoundButton.java:144) 
        at android.view.View.performClickInternal(View.java:7425) 
        at android.view.View.access$3600(View.java:810) 
        at android.view.View$PerformClick.run(View.java:28305) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by shobhitagarwal1612** [comment]
Is the issue still active in crashlytics?

**Comment by gino-m** [comment]
> @gino-m Is the issue still active in crashlytics?

Pilots have ended so we'd need more data to say whether this was still occurring.

**Comment by gino-m** [comment]
Superceded by new data collection flow.
