### ISSUE TITLE
[Delete feature] Exception when trying to delete GeoJSON feature

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#859]
```

2021-06-05 18:32:27.419 12515-12593/com.google.android.gnd E/WM-WorkerWrapper: Work [ id=3f527231-8062-4a76-bba8-8167c213a598, tags={ com.google.android.gnd.persistence.sync.LocalMutationSyncWorker } ] failed because it threw an exception/error
    java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gnd.model.feature.Point com.google.android.gnd.persistence.local.room.models.Coordinates.toPoint()' on a null object reference
        at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
        at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
        at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:298)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gnd.model.feature.Point com.google.android.gnd.persistence.local.room.models.Coordinates.toPoint()' on a null object reference
        at com.google.android.gnd.persistence.local.room.entity.FeatureMutationEntity.toMutation(FeatureMutationEntity.java:90)
        at com.google.android.gnd.persistence.local.room.-$$Lambda$dpsJ_dA-hCj5fxyjCR-k6Y_Pv00.apply(Unknown Source:2)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
        at com.akaita.java.rxjava2debug.extensions.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:55)
        at io.reactivex.internal.operators.single.SingleFlatMapIterableObservable$FlatMapIterableObserver.onSuccess(SingleFlatMapIterableObservable.java:123)
        at com.akaita.java.rxjava2debug.extensions.SingleOnAssembly$OnAssemblySingleObserver.onSuccess(SingleOnAssembly.java:68)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:67)
        at androidx.room.RxRoom$5.subscribe(RxRoom.java:229)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at com.akaita.java.rxjava2debug.extensions.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:41)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMapIterableObservable.subscribeActual(SingleFlatMapIterableObservable.java:47)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at com.akaita.java.rxjava2debug.extensions.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:41)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at com.akaita.java.rxjava2debug.extensions.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:41)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at com.akaita.java.rxjava2debug.extensions.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:41)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
        at com.akaita.java.rxjava2debug.extensions.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:55)
        at io.reactivex.internal.operators.observable.ObservableFromArray$FromArrayDisposable.run(ObservableFromArray.java:108)
        at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:37)
2021-06-05 18:32:27.419 12515-12593/com.google.android.gnd E/WM-WorkerWrapper:     at io.reactivex.Observable.subscribe(Observable.java:12284)
        at com.akaita.java.rxjava2debug.extensions.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:41)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at com.akaita.java.rxjava2debug.extensions.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:41)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at com.akaita.java.rxjava2debug.extensions.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:41)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at com.akaita.java.rxjava2debug.extensions.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:41)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        	... 3 more
     Caused by: com.akaita.java.rxjava2debug.extensions.RxJavaAssemblyException
     Caused by: com.akaita.java.rxjava2debug.extensions.RxJavaAssemblyException
     Caused by: com.akaita.java.rxjava2debug.extensions.RxJavaAssemblyException
     Caused by: com.akaita.java.rxjava2debug.extensions.RxJavaAssemblyException
     Caused by: com.akaita.java.rxjava2debug.extensions.RxJavaAssemblyException
     Caused by: com.akaita.java.rxjava2debug.extensions.RxJavaAssemblyException
2021-06-05 18:32:35.223 1915-1936/system_process E/BatteryExternalStatsWorker: no controller energy info supplied for wifi
2021-06-05 18:32:36.380 7856-8149/com.google.android.apps.messaging E/CarrierServices: [860] iez.getFile: File not found.: /data/user/0/com.google.android.apps.messaging/files/httpft_pending (No such file or directory)
    	java.io.FileInputStream.open0(Native Method)
    	java.io.FileInputStream.open(FileInputStream.java:231)
    	java.io.FileInputStream.<init>(FileInputStream.java:165)
    	android.app.ContextImpl.openFileInput(ContextImpl.java:560)
    	android.content.ContextWrapper.openFileInput(ContextWrapper.java:202)
    	iez.getFile(SourceFile:20)
    	com.google.android.apps.messaging.rcsmigration.RcsStateProvider.buildRcsState(SourceFile:136)
    	com.google.android.apps.messaging.rcsmigration.RcsStateProvider.getRcsState(SourceFile:6)
    	com.google.android.ims.rcsmigration.IRcsStateProvider$Stub.dispatchTransaction(SourceFile:10)
    	com.google.android.aidl.BaseStub.onTransact(SourceFile:18)
    	android.os.Binder.execTransact(Binder.java:731)
```

**Comment by gino-m** [comment]
Closed by https://github.com/google/ground-android/commit/9716ced27d2b129d6f04d99c9a2fa07d7c23180a
