### ISSUE TITLE
[Photo] App crashed and restarted when taking photo

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#895]
After tapped "check" to confirm photo, app crashed a restarted, showing splash screen. Splash screen remains frozen indefinitely.

Seen on physical Pixel 4 API 30.

Potentially relevant Logcat errors:

```
2021-06-16 10:35:26.516 19068-12972/? E/fb4a.6mq: Failure decoding override info
    X.2sW: org.json.JSONException: No value for new_locale
        at X.3ZY.<init>(:98)
        at X.6mq.DxI(:23)
        at X.4Xa.call(:72)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at X.10m.run(:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at X.10r.run(:3)
        at X.11B.run(:12)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: org.json.JSONException: No value for new_locale
        at org.json.JSONObject.get(JSONObject.java:400)
        at org.json.JSONObject.getString(JSONObject.java:561)
        at X.3ZY.<init>(:10)
        at X.6mq.DxI(:23) 
        at X.4Xa.call(:72) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at X.10m.run(:72) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at X.10r.run(:3) 
        at X.11B.run(:12) 
        at java.lang.Thread.run(Thread.java:923) 
```

```
2021-06-16 10:35:27.651 14165-14604/? E/AuthPII: [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: Account {name=gndtestuser@gmail.com, type=com.google}, App: com.google.android.gms, Service: oauth2:https://www.googleapis.com/auth/lams
    svo: Long live credential not available.
        at hml.a(:com.google.android.gms@212116046@21.21.16 (150400-378233385):13)
        at hmo.e(:com.google.android.gms@212116046@21.21.16 (150400-378233385):1)
        at hkz.l(:com.google.android.gms@212116046@21.21.16 (150400-378233385):91)
        at dug.j(:com.google.android.gms@212116046@21.21.16 (150400-378233385):32)
        at dug.c(:com.google.android.gms@212116046@21.21.16 (150400-378233385):42)
        at dug.ei(:com.google.android.gms@212116046@21.21.16 (150400-378233385):11)
        at dsh.onTransact(:com.google.android.gms@212116046@21.21.16 (150400-378233385):5)
        at android.os.Binder.transact(Binder.java:1043)
        at dxa.onTransact(:com.google.android.gms@212116046@21.21.16 (150400-378233385):2)
        at android.os.Binder.transact(Binder.java:1043)
        at ackk.onTransact(:com.google.android.gms@212116046@21.21.16 (150400-378233385):17)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
        at android.os.Binder.execTransact(Binder.java:1123)
2021-06-16 10:35:27.651 14165-14604/? E/AuthPII: Message is Long live credential not available.
    svo: Long live credential not available.
        at hml.a(:com.google.android.gms@212116046@21.21.16 (150400-378233385):13)
        at hmo.e(:com.google.android.gms@212116046@21.21.16 (150400-378233385):1)
        at hkz.l(:com.google.android.gms@212116046@21.21.16 (150400-378233385):91)
        at dug.j(:com.google.android.gms@212116046@21.21.16 (150400-378233385):32)
        at dug.c(:com.google.android.gms@212116046@21.21.16 (150400-378233385):42)
        at dug.ei(:com.google.android.gms@212116046@21.21.16 (150400-378233385):11)
        at dsh.onTransact(:com.google.android.gms@212116046@21.21.16 (150400-378233385):5)
        at android.os.Binder.transact(Binder.java:1043)
        at dxa.onTransact(:com.google.android.gms@212116046@21.21.16 (150400-378233385):2)
        at android.os.Binder.transact(Binder.java:1043)
        at ackk.onTransact(:com.google.android.gms@212116046@21.21.16 (150400-378233385):17)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
        at android.os.Binder.execTransact(Binder.java:1123)
```

@shobhitagarwal1612 Any ideas?

**Comment by gino-m** [comment]
Can't repro now

**Comment by shobhitagarwal1612** [comment]
I have a pixel 4a physical device with android 11.
Wiped app data of gallery, camera and ground app along with all permissions.

Did not observe any crashes. But the photos were appearing sideways in the app.
