### ISSUE TITLE
[Map] Map freezes when upgrading to targetSdk 27 or higher

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#946]
We haven't been able to upgrade past 26 because of issues with Maps SDK when updating to 27 or higher: panning and zooming the map gets progressively slower until the app completely freezes.

Repro:

* Update `targetSdkVersion` to `27` in `gnd/build.gradle`
* Sync, build, and run app on Nexus 5X API 29 in emulator.
* Sign in and join a project.
* Try to pan and zoom the map, app is either frozen or slow to the point of being unusable.

**Comment by gino-m** [comment]
We spoke. The issue is only reproducible when Android SDK strict mode is set (`in GndApplication`). I found some stack traces that might be relevant:

```
2021-08-12 19:22:51.427 29482-29482/com.google.android.gnd D/StrictMode: StrictMode policy violation; ~duration=875 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7246)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:645)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:636)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:592)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:787)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:439)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
        at com.google.android.gnd.GndApplicationModule.provideSharedPreferences(GndApplicationModule.java:55)
        at com.google.android.gnd.GndApplicationModule_ProvideSharedPreferencesFactory.provideSharedPreferences(GndApplicationModule_ProvideSharedPreferencesFactory.java:37)
        at com.google.android.gnd.DaggerGndApplication_HiltComponents_SingletonC.sharedPreferences(DaggerGndApplication_HiltComponents_SingletonC.java:525)
        at com.google.android.gnd.DaggerGndApplication_HiltComponents_SingletonC.localValueStore(DaggerGndApplication_HiltComponents_SingletonC.java:539)
        at com.google.android.gnd.DaggerGndApplication_HiltComponents_SingletonC.userRepository(DaggerGndApplication_HiltComponents_SingletonC.java:712)
        at com.google.android.gnd.DaggerGndApplication_HiltComponents_SingletonC.access$2200(DaggerGndApplication_HiltComponents_SingletonC.java:223)
        at com.google.android.gnd.DaggerGndApplication_HiltComponents_SingletonC$ActivityRetainedCImpl$ActivityCImpl.injectMainActivity2(DaggerGndApplication_HiltComponents_SingletonC.java:1495)
        at com.google.android.gnd.DaggerGndApplication_HiltComponents_SingletonC$ActivityRetainedCImpl$ActivityCImpl.injectMainActivity(DaggerGndApplication_HiltComponents_SingletonC.java:1458)
        at com.google.android.gnd.Hilt_MainActivity.inject(Hilt_MainActivity.java:53)
        at com.google.android.gnd.Hilt_MainActivity.onCreate(Hilt_MainActivity.java:27)
        at com.google.android.gnd.MainActivity.onCreate(MainActivity.java:66)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2021-08-12 19:22:54.764 29482-29482/com.google.android.gnd D/StrictMode: StrictMode policy violation; ~duration=1212 ms: android.os.strictmode.CustomViolation: gcore.dynamite
        at android.os.StrictMode$AndroidBlockGuardPolicy.onCustomSlowCall(StrictMode.java:1523)
        at android.os.StrictMode.noteSlowCall(StrictMode.java:2471)
        at wog.a(:com.google.android.gms@212621040@21.26.21 (120700-387928701):0)
        at com.google.android.gms.chimera.container.GmsModuleChimeraProvider.query(:com.google.android.gms@212621040@21.26.21 (120700-387928701):10)
        at twi.query(:com.google.android.gms@212621040@21.26.21 (120700-387928701):3)
        at android.content.ContentProvider.query(ContentProvider.java:1214)
        at eiw.superQuery(:com.google.android.gms@212621040@21.26.21 (120700-387928701):2)
        at com.google.android.chimera.ContentProvider.query(:com.google.android.gms@212621040@21.26.21 (120700-387928701):2)
        at twi.query(:com.google.android.gms@212621040@21.26.21 (120700-387928701):8)
        at android.content.ContentProvider.query(ContentProvider.java:1307)
        at eiw.superQuery(:com.google.android.gms@212621040@21.26.21 (120700-387928701):1)
        at com.google.android.chimera.ContentProvider.query(:com.google.android.gms@212621040@21.26.21 (120700-387928701):1)
        at eiw.query(:com.google.android.gms@212621040@21.26.21 (120700-387928701):2)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:267)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
    # via Binder call with stack:
        at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:2274)
        at android.os.Parcel.readExceptionCode(Parcel.java:2017)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.google.android.gms.dynamite.DynamiteModule.zzc(com.google.android.gms:play-services-basement@@17.5.0:174)
        at com.google.android.gms.dynamite.DynamiteModule.zza(com.google.android.gms:play-services-basement@@17.5.0:116)
        at com.google.android.gms.dynamite.zzb.zza(com.google.android.gms:play-services-basement@@17.5.0:2)
        at com.google.android.gms.dynamite.zze.zza(com.google.android.gms:play-services-basement@@17.5.0:4)
        at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@17.5.0:7)
        at com.google.android.gms.maps.internal.zzbz.zzc(Unknown Source:35)
        at com.google.android.gms.maps.internal.zzbz.zzb(Unknown Source:32)
        at com.google.android.gms.maps.internal.zzbz.zza(Unknown Source:14)
        at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source:4)
        at com.google.android.gms.maps.SupportMapFragment$zzb.zzd(Unknown Source:9)
        at com.google.android.gms.maps.SupportMapFragment$zzb.createDelegate(Unknown Source:6)
        at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(com.google.android.gms:play-services-base@@17.5.0:18)
        at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(com.google.android.gms:play-services-base@@17.5.0:22)
        at com.google.android.gms.maps.SupportMapFragment.onCreate(Unknown Source:26)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
    	at androidx.fragment.app.FragmentManager.dispatchViewCreated(F
```

**Comment by gino-m** [comment]
Note that disabling `SharedPreferences` eliminates the first exception. I suspect the culprit is something related to GmsModuleChimeraProvider.query().

**Comment by gino-m** [comment]
A recent change to GmsCore exempts it from CUSTOM_SLOW_CALL checks. Upgrading Maps SDK to 17.0.1 seems to solve the problem!
