### ISSUE TITLE
[Crash] When clicking "Add feature" button multiple times

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#980]
Steps to reproduce:

 * Select any project which contains multiple layers
 * Tap the `+` button multiple times before the dialog is able to load
 * The app crashes

Stacktrace:

```
    java.lang.IllegalStateException: Fragment already added: AddFeatureDialogFragment{c60985d} (97a50359-ae75-4d59-a562-cd6c271b0881 tag=AddFeatureDialogFragment)
        at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:91)
        at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1713)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:415)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2404)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2162)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7876)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by nmhung00** [comment]
Looks like this is fixed. I can't reproduce the crash anymore.
