### ISSUE TITLE
App crashed with "Map fragment already initialized"

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#999]
Occurring on a fresh install at HEAD on AS emulator with Nexus 5X API 29. Not sure of exact repro steps yet.

```
2021-08-25 18:28:25.560 8661-8661/com.google.android.gnd E/WindowManager: android.view.WindowLeaked: Activity com.google.android.gnd.MainActivity has leaked window DecorView@e01e221[MainActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:597)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:377)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
        at android.app.Dialog.show(Dialog.java:342)
        at com.google.android.gnd.ui.home.HomeScreenFragment.showProjectLoadingDialog(HomeScreenFragment.java:485)
        at com.google.android.gnd.ui.home.HomeScreenFragment.onActiveProjectChange(HomeScreenFragment.java:429)
        at com.google.android.gnd.ui.home.HomeScreenFragment.lambda$N1alPoKff1duM2PhBC9QtepNGdM(Unknown Source:0)
        at com.google.android.gnd.ui.home.-$$Lambda$HomeScreenFragment$N1alPoKff1duM2PhBC9QtepNGdM.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2021-08-25 18:28:25.797 8661-8661/com.google.android.gnd E/gle.android.gn: Invalid ID 0x00000000.
2021-08-25 18:28:26.295 8661-8661/com.google.android.gnd E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.gnd, PID: 8661
    java.lang.IllegalStateException: Map fragment already initialized
        at com.google.android.gnd.ui.map.gms.GoogleMapsMapProvider.init(GoogleMapsMapProvider.java:55)
        at com.google.android.gnd.ui.map.gms.GoogleMapsMapProvider.restore(GoogleMapsMapProvider.java:50)
        at com.google.android.gnd.ui.home.mapcontainer.MapContainerFragment.onViewCreated(MapContainerFragment.java:149)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at com.google.android.gnd.AbstractActivity.onStart(AbstractActivity.java:73)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
        at android.app.Activity.performStart(Activity.java:7825)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:57)
        at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5238)
        at android.app.ActivityThread.access$3400(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2026)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by gino-m** [comment]
> I can repro this on rotating the screen. This is likely caused due to re-initialisation of the `GoogleMapsMapProvider`.
> 
> We recently made it a singleton to have the same instance shared b/w MapFragment and Reposition/PolyDrawing view.

Should we revert that change, or is there a straightforward fix?

**Comment by shobhitagarwal1612** [comment]
I'm exploring a fix. Will update by EOW.

**Comment by gino-m** [comment]
> I'm exploring a fix. Will update by EOW.

Thank you @shobhitagarwal1612 !
